const DAYS = [
 {n:1,date:'Jue 13 ago',title:'Edimburgo',subtitle:'Llegada y Castillo de Edimburgo',sleep:'Edimburgo',tags:['Castillo','Royal Mile','Old Town'],summary:'Primer contacto con la capital escocesa. El día gira alrededor de la visita reservada al Castillo de Edimburgo a las 15:30, dejando el resto de la jornada deliberadamente flexible.',schedule:[['03:00','Salida de Salobreña hacia el aeropuerto de Málaga.'],['06:10','Vuelo Málaga–Edimburgo.'],['08:30','Llegada prevista a Edimburgo.'],['Mañana','Traslado al Holiday Inn Edinburgh y depósito del equipaje.'],['13:00','Comida sencilla cerca del centro o del castillo.'],['14:45','Reunión en la explanada del castillo.'],['15:30','Visita al Castillo de Edimburgo.'],['Tarde','Castlehill, Royal Mile, Victoria Street o Grassmarket.'],['Noche','Cena y descanso.']],places:[['Edimburgo','Edimburgo se entiende mejor como una ciudad construida en capas. La Old Town creció sobre una cresta rocosa que une Castle Rock con Holyrood; de ese eje surgieron la Royal Mile y una red de closes y wynds que descienden por las laderas. En el siglo XVIII, la New Town ofreció el contraste: calles regulares, plazas, jardines y arquitectura georgiana. La coexistencia de ambas ciudades explica buena parte de su personalidad.'],['Castillo de Edimburgo','La fortaleza ocupa Castle Rock, resto resistente de un antiguo sistema volcánico. Fue residencia real, plaza militar, prisión y símbolo del poder escocés. Dentro se superponen siglos de historia: la capilla de Santa Margarita, el Great Hall, las baterías y las Honours of Scotland.'],['Royal Mile','No es una sola calle, sino una sucesión de tramos —Castlehill, Lawnmarket, High Street y Canongate— que conectan el castillo y Holyrood. Entre ambos se concentran St Giles, edificios institucionales, antiguas casas nobles, patios y pasadizos.'],['Victoria Street y Grassmarket','Victoria Street salva con una curva muy característica el fuerte desnivel entre George IV Bridge y Grassmarket. Este último fue mercado y lugar de ejecuciones públicas; hoy ofrece una de las vistas más potentes del castillo sobre los tejados.']],before:'Edimburgo se entiende mejor mirando el relieve. La ciudad medieval creció donde la roca y las pendientes ofrecían defensa; la ciudad georgiana se diseñó siglos después como una respuesta ordenada, luminosa y racional a la densidad de la Old Town.',recommend:'Al salir del castillo, deteneos un momento en Castlehill y mirad hacia la ciudad antes de seguir bajando.'},
 {n:2,date:'Vie 14 ago',title:'Highlands y Lago Ness',subtitle:'Glen Coe, Fort Augustus, Inverness y Pitlochry',sleep:'Edimburgo',tags:['Tour privado','Highlands','Lago Ness'],summary:'Una jornada completa hacia las Highlands, donde paisaje, geología e historia de los clanes se mezclan de forma especialmente intensa.',schedule:[['07:00','Recogida en el Holiday Inn Edinburgh.'],['Mañana','Parada de café y vacas Highland.'],['Mañana','Glen Coe y paradas paisajísticas.'],['13:00 aprox.','Fort Augustus: comida y crucero opcional.'],['Tarde','Lago Ness e Inverness.'],['Regreso','Parada breve en Pitlochry.'],['20:00','Llegada prevista a Edimburgo.']],places:[['Glen Coe','El dramatismo del valle no procede solo de la altura de las montañas. El paisaje se desarrolló sobre rocas asociadas a una gran actividad volcánica antigua y fue remodelado después por los glaciares, que ensancharon el fondo y cortaron las laderas. También está ligado a la matanza de los MacDonald de 1692, uno de los episodios más recordados de la historia de las Highlands.'],['Fort Augustus','En el extremo sur del Lago Ness, Fort Augustus permite observar las esclusas del Canal de Caledonia, una obra del siglo XIX que enlaza varios lagos naturales a través del Great Glen. Para quien no haga el crucero, el paseo junto a las esclusas es una alternativa excelente.'],['Lago Ness','Más allá de la leyenda de Nessie, el lago forma parte de una profunda fractura geológica que atraviesa Escocia de costa a costa. Sus aguas oscuras y sus laderas largas ayudan a entender la escala del Great Glen.'],['Inverness','Capital de las Highlands y centro natural del norte escocés. El paseo junto al río Ness permite una primera impresión breve y agradable de la ciudad.'],['Pitlochry','Última pausa antes de volver a Edimburgo: baños, bebida y recuento general.']],before:'En Glen Coe, paisaje e historia están inseparablemente unidos: un valle modelado por hielo y volcanismo antiguo que conserva además la memoria de uno de los episodios más conocidos de la historia de los clanes.',recommend:'En Glen Coe, dedica unos segundos a mirar el valle sin cámara. La escala del paisaje se entiende mejor así.'},
 {n:3,date:'Sáb 15 ago',title:'Dunnottar y Saint Andrews',subtitle:'Falkland, Stonehaven, Dundee y costa oriental',sleep:'Edimburgo',tags:['Dunnottar','Saint Andrews','Costa'],summary:'La jornada recorre la costa oriental de Escocia. Dunnottar y Saint Andrews son las prioridades claras; Dundee y Queensferry quedan condicionadas al tiempo disponible.',schedule:[['08:00','Recogida en el hotel.'],['Mañana','Falkland.'],['Mediodía','Stonehaven y miradores.'],['Mediodía','Castillo de Dunnottar.'],['Tarde','Dundee si el horario lo permite.'],['Tarde','Saint Andrews.'],['Regreso','South Queensferry si queda margen.'],['19:00','Regreso previsto a Edimburgo.']],places:[['Falkland','Pequeño pueblo de Fife con un centro histórico bien conservado. Es una parada cómoda para café y paseo; quienes conozcan Outlander reconocerán algunos escenarios.'],['Dunnottar','Las ruinas se levantan sobre un promontorio rocoso casi aislado por acantilados. Su posición era una defensa natural extraordinaria. En el siglo XVII protegió las Honours of Scotland —corona, cetro y espada de Estado— frente a las tropas de Oliver Cromwell.'],['Saint Andrews','Reúne tres identidades: antigua capital religiosa de Escocia, sede de la universidad más antigua del país y referencia mundial del golf. Las ruinas de la catedral hablan de su peso medieval; la universidad se mezcla con las calles; y el Old Course ocupa terrenos de dunas junto al mar.'],['Old Course y West Sands','Aunque nadie juegue al golf, merece la pena acercarse al entorno del hoyo 18 y al puente de piedra. West Sands prolonga el paisaje costero y ayuda a entender por qué el golf nació aquí como un deporte ligado al terreno natural.']],before:'Dunnottar reúne tres elementos difíciles de separar: historia, roca y mar. El promontorio explica por sí solo por qué la fortaleza fue tan difícil de conquistar.',recommend:'Caminad al menos hasta el primer mirador de Dunnottar: allí se entiende la escala completa del lugar.'},
 {n:4,date:'Dom 16 ago',title:'Edimburgo y vuelo a Cork',subtitle:'Última mañana en Escocia y llegada a Irlanda',sleep:'Cork',tags:['Vuelo 19:55','Cork','5 coches'],summary:'Mañana flexible en Edimburgo y vuelo nocturno a Cork. La prioridad real es cambiar de país con margen, recoger los cinco coches y llegar tranquilos al hotel.',schedule:[['Mañana','Desayuno, check-out y depósito de equipaje.'],['10:00 aprox.','Misa católica (por confirmar).'],['11:15–14:30','Paseo flexible por Edimburgo.'],['14:30','Comida ligera.'],['16:00','Recogida de equipaje.'],['16:30–17:00','Salida hacia el aeropuerto.'],['19:55','Vuelo Edimburgo–Cork.'],['21:15','Llegada prevista a Cork.'],['Noche','Recogida de cinco coches y traslado al Clayton Hotel Cork City.']],places:[['Dean Village y Water of Leith','Un paseo muy distinto de la Old Town: antiguos molinos, puentes y viviendas encajadas en el valle del Water of Leith. Es una buena opción si el tiempo acompaña.'],['National Museum of Scotland','Una alternativa excelente con lluvia y apta para edades muy distintas. Sus colecciones recorren historia natural, ciencia, tecnología y cultura escocesa.'],['New Town y Princes Street Gardens','La New Town permite ver el proyecto urbano de la Ilustración. Princes Street Gardens ocupan parte del espacio del antiguo Nor Loch, drenado para permitir la expansión de la ciudad.'],['Llegada a Irlanda','Será el primer contacto con la conducción por la izquierda. Los cinco coches deben poder completar la ruta de forma autónoma y conviene asignar conductores, pasajeros y equipaje antes de salir del aeropuerto.']],before:'La mañana debe ser deliberadamente ligera. El éxito del día no será añadir un monumento más, sino llegar a Irlanda con todo el grupo, el equipaje y los cinco coches bien organizados.',recommend:'No añadáis una visita más si compromete el traslado al aeropuerto.'},
 {n:5,date:'Lun 17 ago',title:'Anillo de Kerry',subtitle:'Killarney, Ladies View, Kenmare, Sneem y Atlántico',sleep:'Cork',tags:['Ruta panorámica','Kerry','Cork'],summary:'Gran jornada paisajística por la península de Iveragh, con regreso a Cork. Aquí el verdadero monumento es la carretera y la sucesión de montañas, lagos y costa.',schedule:[['08:00','Salida desde el Clayton Hotel Cork City.'],['09:30','Killarney: café y baños.'],['10:00','Moll’s Gap y Ladies View.'],['11:00','Kenmare.'],['12:00','Salida hacia Sneem.'],['13:00','Picnic.'],['14:00','Miradores de la costa.'],['15:30','Decisión: continuar o iniciar regreso.'],['18:30–20:00','Llegada estimada a Cork.']],places:[['Killarney National Park','El primer parque nacional de Irlanda protege lagos, bosques de roble y tejo, montañas y una importante población de ciervo rojo. El contraste entre agua, bosque y relieve es una de las claves de la belleza de Killarney.'],['Ladies View','Permite leer el paisaje casi como un mapa: lagos encadenados en primer plano y montañas cerrando el valle. Su nombre se relaciona tradicionalmente con las damas de compañía de la reina Victoria durante la visita real de 1861.'],['Kenmare','Pueblo agradable para una pausa funcional: café, baños y compra de picnic.'],['Sneem','Casas de colores, río y pequeñas plazas. Buen punto para decidir el ritmo de la tarde.'],['Costa atlántica','El atractivo está en la carretera misma: pequeñas playas, bahías, montañas y cambios constantes de luz. No hace falta detenerse en cada mirador.']],before:'El suroeste irlandés debe buena parte de su aspecto a la acción del hielo, el océano y una geología muy antigua. La lluvia breve y la luz cambiante intensifican los colores y transforman el paisaje en pocos minutos.',recommend:'No midáis el éxito por completar el círculo entero; una buena parada tranquila puede ser el mejor recuerdo del día.'},
 {n:6,date:'Mar 18 ago',title:'Cobh, Blarney y Galway',subtitle:'Historia marítima, castillo y cambio de alojamiento',sleep:'Galway',tags:['Cobh','Blarney','Traslado'],summary:'Check-out en Cork, visita a Cobh y Blarney, recogida del equipaje y traslado final a Galway.',schedule:[['08:15','Check-out y depósito de equipaje en el Clayton Hotel Cork City.'],['08:30','Salida hacia Cobh.'],['09:15–12:00','Cobh: catedral, paseo marítimo y Titanic Experience si se reserva.'],['12:00','Comida en Cobh o picnic.'],['13:15','Salida hacia Blarney.'],['14:00–16:30','Castillo y jardines de Blarney.'],['16:30','Regreso al hotel para recoger el equipaje.'],['17:15 aprox.','Salida hacia Galway.'],['Noche','Llegada al Maldron Hotel Sandy Road Galway.']],places:[['Cobh','Uno de los grandes puertos de emigración irlandesa y última escala del Titanic antes de cruzar el Atlántico. La ciudad se comprende mejor recordando que para millones de personas fue la última imagen de Irlanda antes de partir.'],['Catedral de St Colman','Se eleva sobre la ladera y actúa como referencia visual desde casi todo el puerto. Su posición, junto a las fachadas de colores, crea la imagen más reconocible de Cobh.'],['Titanic y emigración','Cuando el Titanic llegó en 1912, Cobh todavía se llamaba Queenstown. Los pasajeros accedieron mediante barcos auxiliares. La historia del transatlántico es solo una parte de una memoria marítima mucho más amplia, vinculada a la Gran Hambruna y a la diáspora irlandesa.'],['Blarney Castle','La gran torre del siglo XV fue levantada por los MacCarthy de Muskerry. La Piedra de Blarney promete el don de la elocuencia a quien la besa, pero el castillo y sus jardines merecen la visita incluso sin participar en el rito.'],['Rock Close y jardines','Senderos, árboles maduros, cursos de agua y rincones asociados a leyendas de druidas y folclore irlandés. Ofrecen una visita mucho más relajada que la subida a la torre.']],before:'Cobh se contempla de otra manera si se piensa que, durante generaciones, este puerto fue el lugar desde el que muchas familias se despedían de Irlanda sin saber si volverían.',recommend:'En Cobh, separaos unos minutos del grupo y mirad el puerto. Pensar en quienes partieron desde allí transforma la visita.'},
 {n:7,date:'Mié 19 ago',title:'Galway, Burren y Moher',subtitle:'Ciudad atlántica, karst y grandes acantilados',sleep:'Galway',tags:['Galway','Burren','Moher'],summary:'Mañana para disfrutar Galway a pie; después, carretera por el Burren y visita a los acantilados de Moher, regresando a Galway.',schedule:[['09:00–12:00','Paseo por Galway: Eyre Square, Shop Street, Spanish Arch y ribera.'],['12:00','Comida temprana o compra de picnic.'],['13:00','Salida hacia los acantilados por la región del Burren.'],['15:00–17:00','Cliffs of Moher Experience.'],['17:00','Regreso hacia Galway.'],['19:00 aprox.','Llegada al hotel y cena.']],places:[['Galway','Antiguo puerto comercial medieval y una de las ciudades con mayor personalidad del oeste de Irlanda. El centro se disfruta caminando: Eyre Square, Shop Street, Quay Street, Spanish Arch y la ribera forman un recorrido compacto, lleno de música y vida urbana.'],['Spanish Arch y Claddagh','El Spanish Arch formaba parte de la ampliación de las murallas junto a los muelles. Hacia el oeste estaba el antiguo barrio pesquero de Claddagh, cuyo nombre está ligado al anillo de dos manos que sostienen un corazón coronado.'],['El Burren','Un paisaje kárstico de grandes losas de caliza separadas por grietas. Bajo su apariencia austera existe una red de fisuras, cuevas y conductos. En pequeñas grietas conviven especies atlánticas, alpinas y mediterráneas, una combinación botánica excepcional.'],['Acantilados de Moher','Estratos alternos de areniscas, limos y lutitas forman una pared que el Atlántico sigue modelando mediante erosión y desprendimientos. Con sol, lluvia o niebla, el color de la roca cambia continuamente.'],['O’Brien’s Tower','Mirador del siglo XIX situado en uno de los puntos más altos. Con buena visibilidad pueden distinguirse las islas Aran y, hacia el norte, las costas de Connemara.']],before:'Moher no es un lugar para acercarse al borde, sino para contemplar la escala del paisaje desde los miradores seguros. El viento, las aves y el sonido del océano forman parte de la experiencia.',recommend:'Guardad el teléfono durante un minuto. La sensación de altura, viento y distancia no cabe en una fotografía.'},
 {n:8,date:'Jue 20 ago',title:'Dublín y regreso',subtitle:'Un paseo breve antes del aeropuerto',sleep:'Casa',tags:['Dublín','Vuelo 15:30','Regreso'],summary:'Desde Galway a Dublín con poco margen. El paseo por la capital es opcional y debe cancelarse si compromete la llegada al aeropuerto.',schedule:[['06:45','Desayuno, check-out y carga de coches en Galway.'],['07:15','Salida hacia Dublín.'],['09:45 aprox.','Llegada a un aparcamiento céntrico, solo si el tráfico lo permite.'],['10:00–11:15','Paseo breve: Christ Church, Dublin Castle, Dame Street y borde de Temple Bar.'],['11:15','Salida hacia el aeropuerto.'],['12:00','Repostaje y devolución de los cinco coches.'],['13:00','Grupo reunido en la terminal.'],['15:30','Vuelo Dublín–Málaga.'],['19:30','Llegada prevista a Málaga.']],places:[['Christ Church y Dublin Castle','El recorrido permite atravesar distintas capas de la historia de Dublín: Christ Church recuerda la ciudad medieval y Dublin Castle fue durante siglos el centro del poder inglés y británico en Irlanda.'],['Temple Bar','Más allá de los pubs más concurridos, conserva una trama de calles estrechas con espacios culturales, librerías, salas de música y pequeños comercios. A primera hora se recorre con más tranquilidad.'],['Dublín literario','Jonathan Swift, Oscar Wilde, W. B. Yeats, James Joyce y Samuel Beckett están vinculados a la ciudad. La literatura, el teatro y la conversación forman parte de su identidad tanto como los monumentos.'],['Orígenes de la ciudad','Dublín creció a partir de núcleos gaélicos y vikingos. El nombre inglés procede de Dubh Linn, “laguna negra”, y el nombre irlandés, Baile Átha Cliath, recuerda un antiguo vado del Liffey.'],['Trinity College','Si en otro viaje hubiera más tiempo, Trinity College y el Book of Kells serían dos referencias fundamentales. En esta ocasión, la breve visita debe centrarse en el corazón histórico y en llegar al aeropuerto sin tensión.']],before:'No vais a conocer Dublín en una hora. Pero sí podéis cruzar algunas de sus capas históricas, llevaros una primera impresión y cerrar el viaje con calma.',recommend:'Si a las 09:45 no estáis aparcando en el centro, id directamente al aeropuerto.'}
];

const DAY_POINTS={1:[["Holiday Inn Edinburgh",55.9429,-3.272],["Edinburgh Castle",55.9486,-3.1999],["Royal Mile",55.95,-3.187],["Grassmarket",55.9473,-3.1954]],2:[["Edinburgh",55.9533,-3.1883],["Glen Coe",56.6826,-5.1023],["Fort Augustus",57.144,-4.68],["Loch Ness",57.3229,-4.4244],["Inverness",57.4778,-4.2247],["Pitlochry",56.702,-3.734]],3:[["Edinburgh",55.9533,-3.1883],["Falkland",56.252,-3.206],["Dunnottar Castle",56.945,-2.197],["Dundee",56.462,-2.9707],["Saint Andrews",56.3398,-2.7967]],4:[["Edinburgh",55.9533,-3.1883],["Edinburgh Airport",55.9508,-3.3615],["Cork Airport",51.8413,-8.4911],["Clayton Hotel Cork City",51.8992,-8.464]],5:[["Cork",51.8985,-8.4756],["Killarney",52.0599,-9.5044],["Ladies View",51.9668,-9.5931],["Kenmare",51.88,-9.583],["Sneem",51.838,-9.9],["Waterville",51.827,-10.171]],6:[["Clayton Hotel Cork City",51.8992,-8.464],["Cobh",51.8507,-8.294],["Blarney Castle",51.9291,-8.5706],["Galway",53.2707,-9.0568]],7:[["Galway",53.2707,-9.0568],["Burren",53.115,-9.15],["Cliffs of Moher",52.9715,-9.4309],["Galway",53.2707,-9.0568]],8:[["Galway",53.2707,-9.0568],["Dublin Castle",53.3429,-6.2675],["Dublin Airport",53.4264,-6.2499]]};
const PHOTOS={1:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Edinburgh%20panorama%20from%20the%20castle.jpg?width=1800",caption:"Edimburgo desde el castillo",credit:"Chinnie666 · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Edinburgh_panorama_from_the_castle.jpg"},2:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Glencoe%2C%20Scotland%2C%20UK.jpg?width=1600",caption:"Glen Coe",credit:"Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Glencoe,_Scotland,_UK.jpg"},3:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Dunnottar%20Castle%20%28Scotland%29.jpg?width=1600",caption:"Dunnottar",credit:"Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Dunnottar_Castle_(Scotland).jpg"},4:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Edinburgh%20panorama%20from%20the%20castle.jpg?width=1800",caption:"Edimburgo",credit:"Chinnie666 · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Edinburgh_panorama_from_the_castle.jpg"},5:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Ladies%20view%20killarney.jpg?width=1600",caption:"Ladies View",credit:"Ianmoran87 · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Ladies_view_killarney.jpg"},6:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Cobh%20Harbour%20Cathedral.jpg?width=1400",caption:"Cobh",credit:"Kondephy · Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Cobh_Harbour_Cathedral.jpg"},7:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Cliffs%20of%20Moher%2C%20Ireland.JPG?width=1600",caption:"Cliffs of Moher",credit:"Jac31 · Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Cliffs_of_Moher,_Ireland.JPG"},8:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Dublin%20Castle.jpg?width=1600",caption:"Dublin Castle",credit:"Mike Peel · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Dublin_Castle.jpg"}};

const HOTELS = [
 {city:'Edimburgo',name:'Holiday Inn Edinburgh',address:'132 Corstorphine Road, Edinburgh',nights:'13, 14 y 15 de agosto',phone:'',email:'',note:'Base durante los tres primeros días en Escocia.'},
 {city:'Cork',name:'Clayton Hotel Cork City',address:'Lapps Quay, Cork, Co. Cork, Irlanda',nights:'16 y 17 de agosto',phone:'+353 21 422 4900',email:'res.corkcity@claytonhotels.com',note:'Check-in 16:00 · check-out 12:00. El bono indica que no dispone de aparcamiento privado; hay aparcamiento público en Lapps Quay con tarifa reducida para residentes hasta las 12:00 del día de salida.'},
 {city:'Galway',name:'Maldron Hotel Sandy Road Galway',address:'Headford Point, Headford Road, Galway City, Co. Galway, H91 ET6N, Irlanda',nights:'18 y 19 de agosto',phone:'+353 91 513 200',email:'reservations.sandyroad@maldronhotels.com',note:'Check-in 16:00 · check-out 12:00. El bono indica aparcamiento disponible con posibles cargos adicionales y Wi‑Fi incluido.'}
];

const HISTORY = {
 scotland:{title:'Escocia: claves para entender el viaje',intro:'El paisaje escocés es inseparable de su historia. Durante siglos, montañas, valles y estuarios fueron fronteras, vías de comunicación y refugios naturales. Las Highlands, los castillos y las ciudades de la costa oriental forman parte de una historia marcada por la construcción de un reino propio, la relación con Inglaterra y una identidad cultural muy resistente.',sections:[
 ['De los pictos al reino de Escocia','En la Antigüedad tardía y la Alta Edad Media, el territorio estaba dividido entre pictos, gaélicos de Dál Riata, britanos de Strathclyde y anglos. A partir del siglo IX fue tomando forma el reino de Alba, núcleo del futuro reino de Escocia, mientras las islas y las Highlands conservaron durante mucho tiempo estructuras de poder vinculadas a clanes y señoríos locales.'],
 ['Las guerras de independencia','A finales del siglo XIII, una crisis sucesoria permitió a Eduardo I de Inglaterra intervenir directamente en Escocia. William Wallace encabezó una de las primeras resistencias y Robert the Bruce consolidó después su posición como rey. La victoria de Bannockburn en 1314 fue decisiva, y la Declaración de Arbroath de 1320 se convirtió siglos después en un texto central de la memoria política escocesa.'],
 ['Estuardo, Reforma y unión de las coronas','La dinastía Estuardo ocupó el trono escocés desde el siglo XIV. María Estuardo es una de sus figuras más conocidas. La Reforma de 1560 impulsó un profundo giro hacia el protestantismo presbiteriano. En 1603, Jacobo VI de Escocia heredó también el trono inglés como Jacobo I: dos coronas quedaron en manos del mismo monarca, aunque los reinos mantuvieron instituciones separadas.'],
 ['1707, jacobitas y Culloden','Los Actos de Unión de 1707 crearon el Reino de Gran Bretaña. Escocia conservó instituciones propias como su sistema jurídico, su Iglesia y una fuerte tradición educativa. Las rebeliones jacobitas de 1715 y 1745 intentaron restaurar a los Estuardo. La derrota de Culloden en 1746 marcó el final de aquel proyecto y abrió una profunda transformación de las Highlands.'],
 ['Ilustración y Escocia contemporánea','Durante los siglos XVIII y XIX, Escocia tuvo un papel extraordinario en filosofía, economía, geología, medicina, ingeniería e industria. Hume, Adam Smith, James Watt y James Hutton son algunos nombres de ese periodo. Desde 1999 Escocia cuenta de nuevo con un Parlamento propio para numerosas materias, dentro del Reino Unido.']
 ]},
 ireland:{title:'Irlanda: historia para entender el paisaje y las ciudades',intro:'Irlanda tiene una historia distinta de la británica, aunque ambas están profundamente entrelazadas. Puertos de emigración, castillos de familias gaélicas, ciudades comerciales y monumentos políticos cuentan etapas muy diferentes de una misma historia insular.',sections:[
 ['Del mundo gaélico a los monasterios','Mucho antes de la llegada de los ingleses, Irlanda estaba organizada en numerosos reinos y señoríos gaélicos. Desde el siglo V, la expansión del cristianismo transformó la isla y los monasterios se convirtieron en centros religiosos, educativos y artísticos de enorme importancia.'],
 ['Vikingos y anglonormandos','Desde finales del siglo VIII, los vikingos atacaron y después fundaron asentamientos permanentes, entre ellos Dublín, Waterford y Limerick. En 1169 llegaron los primeros señores anglonormandos, iniciando una presencia política inglesa que durante siglos fue desigual y convivió con poderes gaélicos y linajes normandos progresivamente integrados.'],
 ['Dominio inglés y transformación religiosa','La expansión del control inglés se intensificó en la Edad Moderna, acompañada por confiscaciones de tierras, plantaciones y fuertes conflictos religiosos y políticos. La identidad católica de gran parte de la población quedó enfrentada a un poder estatal protestante durante siglos.'],
 ['La Gran Hambruna y la emigración','Entre 1845 y 1852, una plaga destruyó repetidamente la cosecha de patata. La crisis, agravada por la pobreza estructural y las relaciones de propiedad, causó alrededor de un millón de muertes y una emigración masiva. Puertos como Cobh se convirtieron en símbolos de aquella diáspora.'],
 ['Independencia, partición y República','El Levantamiento de Pascua de 1916, la guerra de independencia de 1919-1921 y el Tratado Anglo-Irlandés condujeron al Estado Libre Irlandés. Seis condados del noreste permanecieron en el Reino Unido como Irlanda del Norte. La actual República de Irlanda se formalizó en 1949. El Acuerdo de Viernes Santo de 1998 creó un marco político para superar décadas de conflicto en Irlanda del Norte.']
 ]}
};

const practical = [
 ['Documentación','Pasaporte en vigor. ETA del Reino Unido para cada viajero que la necesite, incluidos menores. Tarjeta Sanitaria Europea, seguro de viaje, permisos de conducir y copias digitales de reservas.'],
 ['Equipaje','Capas, impermeable real, calzado cómodo, mochila pequeña por familia, medicación, baterías externas y adaptadores tipo G.'],
 ['Dinero','Escocia utiliza libra esterlina; Irlanda, euro. Conviene pagar en moneda local cuando el terminal ofrezca conversión.'],
 ['Cinco coches','Asignación fija de personas y equipaje. Un conductor principal y uno suplente por coche si el contrato lo permite. Coches A, B, C, D y E.'],
 ['Conducción por la izquierda','En rotondas se circula en sentido horario. Programar destinos antes de iniciar la marcha y usar puntos de reunión concretos, no convoy cerrado.'],
 ['Emergencias','Reino Unido: 999 / 112 · Irlanda: 112 / 999.']
];


const ROUTES = {
  1:{mode:'walking',points:['Holiday Inn Edinburgh','Edinburgh Castle','Royal Mile Edinburgh','Grassmarket Edinburgh']},
  2:{mode:'driving',points:['Edinburgh','Glen Coe Scotland','Fort Augustus','Inverness','Pitlochry','Edinburgh']},
  3:{mode:'driving',points:['Edinburgh','Falkland Fife','Dunnottar Castle','Dundee','St Andrews Scotland','Edinburgh']},
  5:{mode:'driving',points:['Clayton Hotel Cork City','Killarney','Ladies View Killarney','Kenmare','Sneem','Clayton Hotel Cork City']},
  6:{mode:'driving',points:['Clayton Hotel Cork City','Cobh','Blarney Castle','Clayton Hotel Cork City','Maldron Hotel Sandy Road Galway']},
  7:{mode:'driving',points:['Maldron Hotel Sandy Road Galway','The Burren Ireland','Cliffs of Moher','Maldron Hotel Sandy Road Galway']},
  8:{mode:'driving',points:['Maldron Hotel Sandy Road Galway','Dublin Castle','Dublin Airport']}
};

const PLACE_DETAILS = {
 'edimburgo':{title:'Edimburgo',country:'Escocia',day:1,lead:'Una capital construida sobre un relieve extraordinario, donde la ciudad medieval y la ciudad georgiana conviven a ambos lados de un antiguo valle.',sections:[
  ['Una ciudad que se entiende desde el terreno','Edimburgo no se desarrolló sobre una llanura. La Old Town ocupa una cresta rocosa que desciende desde Castle Rock hacia Holyrood, mientras que al norte se abre la depresión donde estuvo el Nor Loch. Esta topografía condicionó las calles, las defensas y hasta la forma de crecer de la ciudad. Por eso la Royal Mile actúa como una auténtica espina dorsal: desde ella parten closes y wynds que bajan por las laderas.'],
  ['De burgo medieval a capital ilustrada','La ciudad creció alrededor de la fortaleza y de la corte real. Durante siglos la población se concentró en un espacio muy reducido, con edificios altos y calles estrechas. En el siglo XVIII, la creación de la New Town cambió por completo la escala urbana. Sus calles rectas, plazas y fachadas georgianas reflejan la confianza de la Ilustración escocesa y contrastan con la densidad de la ciudad medieval.'],
  ['La Ilustración escocesa','Edimburgo fue uno de los grandes centros intelectuales europeos del siglo XVIII. David Hume, Adam Smith, James Hutton y otros pensadores participaron en un ambiente de debate que dejó huella en filosofía, economía, ciencia y medicina. Esa tradición explica la importancia de instituciones como la universidad, los museos y las sociedades científicas.'],
  ['Qué merece la pena observar','Más que intentar completar una lista de monumentos, conviene mirar cómo se relacionan el castillo, la Royal Mile, los jardines y la New Town. Desde un punto elevado se entiende enseguida que las distintas etapas históricas de Edimburgo están escritas sobre el propio relieve.']
 ]},
 'castillo-de-edimburgo':{title:'Castillo de Edimburgo',country:'Escocia',day:1,lead:'Fortaleza, residencia real y símbolo nacional sobre Castle Rock.',sections:[
  ['Castle Rock','La roca del castillo es el resto resistente de un antiguo complejo volcánico. La erosión y los glaciares eliminaron materiales más blandos y dejaron una posición abrupta por tres lados, con un acceso más fácil desde el este. Esa combinación explica por qué el lugar tuvo un valor defensivo excepcional.'],
  ['Una fortaleza de muchas épocas','El conjunto no responde a un único proyecto. La capilla de Santa Margarita, del siglo XII, es el edificio conservado más antiguo; el Great Hall recuerda la etapa cortesana y real; y baterías, cuarteles y prisiones muestran el uso militar posterior. Recorrer el castillo es recorrer siglos de transformaciones.'],
  ['Las Honours of Scotland y la Stone of Destiny','Las joyas de la Corona escocesa se cuentan entre las insignias reales más antiguas conservadas en Europa. Junto a ellas se muestra la Stone of Destiny, vinculada durante siglos a las ceremonias de coronación de los reyes de Escocia.'],
  ['Qué no perderse','Crown Square, la capilla de Santa Margarita, el Great Hall y las vistas sobre la ciudad justifican la visita incluso si alguna de las zonas interiores tiene cola.']
 ]},
 'glen-coe':{title:'Glen Coe',country:'Escocia',day:2,lead:'Uno de los paisajes más poderosos de las Highlands y un lugar donde geología e historia se superponen.',sections:[
  ['Un valle modelado por el hielo','Las rocas de Glen Coe se relacionan con una actividad volcánica muy antigua, pero la forma actual del valle se debe sobre todo a los glaciares. El hielo ensanchó el fondo, recortó las laderas y dejó el perfil en U que se reconoce desde la carretera. Las Three Sisters y Buachaille Etive Mòr son algunas de las referencias visuales más conocidas.'],
  ['La matanza de 1692','Glen Coe está asociado a un episodio especialmente oscuro de la historia escocesa. Soldados del Gobierno fueron alojados por los MacDonald durante casi dos semanas y recibieron después la orden de atacar a sus anfitriones. Murieron decenas de personas y otras fallecieron al huir durante el invierno. La memoria del suceso permanece ligada al valle por la ruptura de las normas tradicionales de hospitalidad.'],
  ['Cómo disfrutar la parada','No hace falta caminar grandes distancias. Desde los miradores de carretera se aprecia bien la escala del paisaje. Merece la pena observar el fondo relativamente abierto del valle y las laderas que ascienden con brusquedad: son las huellas más claras de su origen glaciar.']
 ]},
 'lago-ness':{title:'Lago Ness',country:'Escocia',day:2,lead:'Un lago célebre por Nessie, pero geológicamente mucho más interesante de lo que su leyenda sugiere.',sections:[
  ['El Great Glen','Loch Ness forma parte del Great Glen, una gran línea de fractura que atraviesa Escocia de suroeste a nordeste. Los glaciares aprovecharon esa debilidad de la corteza y profundizaron el valle, creando una cadena de lagos largos y estrechos.'],
  ['Agua oscura y gran profundidad','El color oscuro del agua se debe en parte a materia orgánica procedente de las turberas. Esa apariencia, combinada con la profundidad del lago y la frecuencia de nieblas, ha contribuido a la atmósfera que rodea las historias sobre el monstruo.'],
  ['Nessie','Los relatos modernos sobre una criatura en el lago adquirieron fama internacional en el siglo XX. No existe evidencia científica que demuestre la presencia de un gran animal desconocido, pero la leyenda se ha convertido en parte inseparable de la cultura popular de las Highlands.']
 ]},
 'dunnottar':{title:'Castillo de Dunnottar',country:'Escocia',day:3,lead:'Una fortaleza espectacular cuyo verdadero sistema defensivo era el propio promontorio.',sections:[
  ['Una posición casi inexpugnable','El castillo ocupa una plataforma rocosa rodeada de acantilados y conectada con tierra por un acceso estrecho. Esa geometría permitía defender el lugar con relativamente pocos hombres. La imagen actual es fruto de siglos de reformas y reúne edificios militares, residenciales y de servicio.'],
  ['Las joyas de la Corona','En el siglo XVII, durante la campaña de Oliver Cromwell, las Honours of Scotland fueron llevadas a Dunnottar para impedir su captura. Tras un prolongado asedio, lograron sacarse y ocultarse hasta la restauración de la monarquía. El episodio reforzó el papel simbólico del castillo en la historia nacional.'],
  ['Antes de bajar','El acceso interior implica bastantes escalones. Incluso quien no entre debería caminar hasta el primer mirador: es allí donde se comprende la relación entre la fortaleza, el istmo y el Mar del Norte.']
 ]},
 'saint-andrews':{title:'Saint Andrews',country:'Escocia',day:3,lead:'Una pequeña ciudad con tres identidades extraordinarias: religión, universidad y golf.',sections:[
  ['Capital religiosa medieval','Durante la Edad Media, Saint Andrews fue el principal centro eclesiástico de Escocia. La gran catedral fue lugar de peregrinación y una de las instituciones religiosas más poderosas del reino. Sus ruinas permiten imaginar la escala que tuvo antes de la Reforma del siglo XVI.'],
  ['La universidad','Fundada a comienzos del siglo XV, la University of St Andrews es la más antigua de Escocia. No forma un campus aislado: colegios, patios y edificios académicos están integrados en el casco urbano, algo que explica el ambiente de la ciudad.'],
  ['La cuna del golf','Los links costeros de Saint Andrews están vinculados a los orígenes y a la codificación del golf moderno. El Old Course se desarrolló sobre dunas y terrenos naturales junto al mar. El pequeño Swilcan Bridge, cerca del hoyo 18, es una de las imágenes más reconocibles del deporte.']
 ]},
 'anillo-de-kerry':{title:'Anillo de Kerry',country:'Irlanda',day:5,lead:'Una ruta panorámica donde el paisaje, y no un monumento concreto, es el verdadero protagonista.',sections:[
  ['La península de Iveragh','El recorrido atraviesa una península montañosa y muy recortada por el Atlántico. Los glaciares modelaron valles y cubetas lacustres, mientras el mar y los ríos terminaron de dibujar playas, cabos y ensenadas.'],
  ['Killarney y Ladies View','Los lagos de Killarney, los bosques y las montañas forman uno de los paisajes clásicos de Irlanda. Desde Ladies View se percibe con claridad la sucesión de lagos y relieves. El nombre se relaciona tradicionalmente con las damas de compañía de la reina Victoria durante su visita de 1861.'],
  ['La carretera como parte de la visita','En Kerry no tiene sentido medir el éxito por el número de paradas. La luz cambia con rapidez y cada curva ofrece una relación distinta entre montaña y mar. Para un grupo grande resulta mucho más agradable elegir pocos miradores y detenerse con tiempo.']
 ]},
 'cobh':{title:'Cobh',country:'Irlanda',day:6,lead:'Un puerto de casas de colores cuya historia está marcada por la emigración y las despedidas.',sections:[
  ['La puerta de salida de Irlanda','Durante los siglos XIX y XX, Cobh fue uno de los principales puertos de salida de emigrantes irlandeses. La Gran Hambruna aceleró un proceso que continuó durante generaciones. Para muchas familias, este puerto fue la última imagen de Irlanda antes de partir hacia Gran Bretaña, Norteamérica o Australia.'],
  ['Queenstown y el Titanic','Entre 1849 y 1920 la ciudad se llamó Queenstown. El 11 de abril de 1912, el Titanic hizo aquí su última escala antes de cruzar el Atlántico. El buque permaneció fondeado y los pasajeros llegaron hasta él en embarcaciones auxiliares. La historia del Titanic es famosa, pero es solo una parte de la memoria marítima de Cobh.'],
  ['St Colman y la imagen del puerto','La catedral de St Colman domina la ladera y sirve de referencia desde la bahía. La combinación de pendientes, fachadas de colores y el gran edificio neogótico explica la imagen más conocida de la localidad.']
 ]},
 'blarney-castle':{title:'Blarney Castle & Gardens',country:'Irlanda',day:6,lead:'Mucho más que la famosa piedra: una casa-torre gaélica rodeada de jardines y leyendas.',sections:[
  ['Los MacCarthy','La gran torre fue construida en el siglo XV por los MacCarthy de Muskerry. Como otras casas-torre irlandesas, combinaba funciones residenciales, defensivas y representativas. Las escaleras estrechas y los espacios compactos recuerdan que la seguridad importaba tanto como la comodidad.'],
  ['La Piedra de Blarney','La tradición afirma que quien besa la piedra recibe el don de la elocuencia. Existen varias leyendas sobre su origen y ninguna explicación histórica definitiva. Conviene entender el beso como un rito popular que ha acabado formando parte de la identidad turística del castillo.'],
  ['Los jardines','Rock Close, los senderos, los cursos de agua y los árboles maduros permiten una visita muy diferente a la subida a la torre. Son especialmente útiles para quienes prefieran evitar escaleras o colas.']
 ]},
 'galway':{title:'Galway',country:'Irlanda',day:7,lead:'Una ciudad atlántica que se disfruta tanto por su ambiente como por sus monumentos.',sections:[
  ['Puerto medieval y Tribes of Galway','Galway prosperó como puerto comercial y mantuvo relaciones con Gran Bretaña y la Europa atlántica. Durante siglos, varias familias mercantiles dominaron la vida urbana y fueron conocidas como las Tribes of Galway. El casco histórico conserva la escala compacta de aquella ciudad comercial.'],
  ['Spanish Arch y Claddagh','El Spanish Arch formaba parte de las defensas junto a los muelles y su nombre recuerda la tradición comercial con la península ibérica. Al otro lado del Corrib se encontraba Claddagh, antiguo barrio pesquero asociado al conocido anillo de manos, corazón y corona.'],
  ['Música y vida en la calle','Shop Street y Quay Street concentran músicos, pubs, pequeños comercios y restaurantes. Galway se entiende mejor dejando algo de tiempo libre que intentando seguir una lista rígida de visitas.']
 ]},
 'el-burren':{title:'El Burren',country:'Irlanda',day:7,lead:'Un paisaje calizo aparentemente desnudo que esconde una extraordinaria diversidad natural y una larga presencia humana.',sections:[
  ['Un paisaje kárstico','La superficie está formada por grandes losas de caliza separadas por grietas. El agua se infiltra con rapidez y circula bajo tierra, creando cavidades, cuevas y conductos. Esa falta de agua superficial contribuye a la apariencia austera del territorio.'],
  ['Una flora inesperada','En las grietas protegidas crecen especies que normalmente asociaríamos a regiones muy diferentes. Plantas atlánticas, alpinas y mediterráneas pueden encontrarse muy próximas entre sí gracias a la combinación de microclimas, roca caliza y prácticas ganaderas tradicionales.'],
  ['Paisaje cultural','Muros de piedra seca, restos arqueológicos y pequeñas explotaciones recuerdan que el Burren no es un espacio vacío. Las comunidades humanas se han adaptado durante milenios a un suelo que a primera vista parece poco favorable.']
 ]},
 'acantilados-de-moher':{title:'Acantilados de Moher',country:'Irlanda',day:7,lead:'Una pared de roca frente al Atlántico donde la geología, el viento y las aves forman una sola experiencia.',sections:[
  ['Cómo se formaron','Los acantilados están compuestos por capas de areniscas, limos y lutitas depositadas hace cientos de millones de años. La erosión marina socava la base y abre fracturas; los desprendimientos resultantes mantienen el frente abrupto.'],
  ['Una colonia de aves marinas','Los cortados ofrecen lugares de nidificación inaccesibles para muchos depredadores. En temporada pueden verse fulmares, araos, alcas y, con algo de suerte, frailecillos. Unos pequeños prismáticos ayudan mucho más que acercarse al borde.'],
  ['La experiencia depende del tiempo','Sol, lluvia, niebla y viento cambian por completo la percepción del lugar. La roca puede pasar del ocre al gris casi negro en minutos. No hace falta un cielo despejado para disfrutar de Moher: el mal tiempo puede intensificar su carácter atlántico.']
 ]},
 'dublin':{title:'Dublín',country:'Irlanda',day:8,lead:'Una capital compacta, literaria y atravesada por capas de historia vikinga, medieval, británica e independiente.',sections:[
  ['De Dubh Linn a la capital','La ciudad creció a partir de asentamientos gaélicos y vikingos junto al Liffey. El nombre inglés procede de Dubh Linn, “laguna negra”, mientras que Baile Átha Cliath, el nombre irlandés, recuerda un antiguo vado. Su posición portuaria convirtió a Dublín en centro político y comercial.'],
  ['Christ Church y Dublin Castle','Christ Church conserva la memoria de la ciudad medieval. Muy cerca, Dublin Castle fue durante siglos la sede del poder inglés y posteriormente británico en Irlanda. Caminar entre ambos permite recorrer, en pocos minutos, buena parte de la historia institucional de la capital.'],
  ['Una ciudad literaria','Swift, Wilde, Yeats, Joyce y Beckett son solo algunos de los escritores ligados a Dublín. La literatura está presente en bibliotecas, teatros, pubs y en la propia imagen cultural de la ciudad. Incluso en una visita breve conviene recordar que su prestigio no depende únicamente de los monumentos.'],
  ['Temple Bar con perspectiva','El barrio es conocido por los pubs, pero también concentra espacios culturales y una trama de calles que merece recorrerse antes de que se llene. A primera hora ofrece una impresión mucho más tranquila.']
 ]}
};

function slugify(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,'y').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function routeLink(n){const r=ROUTES[n]; if(!r) return null; const p=r.points; const origin=p[0], destination=p[p.length-1], waypoints=p.slice(1,-1).join('|'); return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}${waypoints?`&waypoints=${encodeURIComponent(waypoints)}`:''}&travelmode=${r.mode}`;}
function detailFor(name){return PLACE_DETAILS[slugify(name)] || null;}

function mapsLink(q){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function todayNumber(){const now=new Date(); if(now.getFullYear()!==2026||now.getMonth()!==7) return null; const d=now.getDate(); return d>=13&&d<=20?d-12:null;}
function dayCard(d){const today=todayNumber()===d.n?' today':'';return `<a class="card day-card${today}" href="#dia-${d.n}"><div class="day-number">Día ${d.n} · ${d.date}</div><h3>${d.title}</h3><p>${d.subtitle}</p><div class="badges">${d.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div></a>`}
function renderHome(){const t=todayNumber(),hero=PHOTOS[1];return `<section class="hero hero-photo" id="inicio" style="--hero-image:url('${hero.url}')"><div class="hero-inner"><div class="eyebrow">13–20 agosto 2026 · 23 viajeros</div><h1>Escocia e Irlanda en familia</h1><p>Guía digital con itinerario, contexto, hoteles, mapas y datos prácticos para consultar durante el viaje.</p><div class="hero-actions"><a class="btn" href="#dias">Ver los 8 días</a><a class="btn secondary" href="#historia">Historia y contexto</a></div><div class="stats"><div class="stat"><strong>8</strong><span>días</span></div><div class="stat"><strong>2</strong><span>países</span></div><div class="stat"><strong>23</strong><span>viajeros</span></div><div class="stat"><strong>5</strong><span>coches en Irlanda</span></div></div><div class="photo-credit"><a href="${hero.source}" target="_blank">Foto: ${hero.credit}</a></div></div></section>${t?`<section class="container"><div class="today-panel"><div class="card today-main"><div class="eyebrow">Hoy toca</div><h2>Día ${t} · ${DAYS[t-1].title}</h2><p>${DAYS[t-1].summary}</p><a class="btn secondary" href="#dia-${t}">Abrir jornada</a></div><div class="card today-side"><div><div class="day-number">Dormimos en</div><div class="big">${DAYS[t-1].sleep}</div></div><div class="muted">${DAYS[t-1].date}</div></div></div></section>`:''}<section class="container"><div class="section-title"><div><div class="eyebrow" style="color:var(--accent-2)">Mapa general</div><h2>La ruta completa</h2></div><p>Mapa interactivo orientativo de Escocia e Irlanda.</p></div><div class="map-card"><div id="tripMap" class="map"></div></div></section><section class="container" id="dias"><div class="section-title"><div><div class="eyebrow" style="color:var(--accent-2)">Itinerario</div><h2>El viaje de un vistazo</h2></div><p>Toca cualquier jornada para abrir horarios, lugares, contexto y recomendaciones.</p></div><div class="grid">${DAYS.map(dayCard).join('')}</div></section><section class="container home-links"><div class="grid"><a class="card feature-link" href="#historia"><div class="day-number">Antes de viajar</div><h3>Historia de Escocia e Irlanda</h3><p>Dos introducciones pensadas para entender mejor lo que iremos viendo.</p></a><a class="card feature-link" href="#lugares"><div class="day-number">Lectura</div><h3>Lugares del viaje</h3><p>Fichas ampliadas para leer antes de cada parada.</p></a><a class="card feature-link" href="#hoteles"><div class="day-number">Alojamiento</div><h3>Hoteles y datos de contacto</h3><p>Direcciones, teléfonos, noches y acceso rápido a Google Maps.</p></a></div></section>`}
function renderDay(n){
 const d=DAYS.find(x=>x.n===n)||DAYS[0],ph=PHOTOS[d.n],route=routeLink(d.n);
 return `<section class="day-hero day-photo" style="--day-image:url('${ph.url}')"><div class="container"><a class="back" href="#dias">← Todos los días</a><div class="eyebrow">Día ${d.n} · ${d.date} · Noche: ${d.sleep}</div><h1>${d.title}</h1><p>${d.subtitle}</p><div class="day-progress"><span style="width:${d.n/8*100}%"></span></div><div class="photo-credit"><a href="${ph.source}" target="_blank">Foto: ${ph.credit}</a></div></div></section><section class="container"><div class="card"><h2>Resumen del día</h2><p>${d.summary}</p></div><div class="section-title"><div><div class="eyebrow" style="color:var(--accent-2)">Ruta</div><h2>Mapa de la jornada</h2></div><p>Marcadores orientativos de las principales paradas.</p></div><div class="map-card"><div id="dayMap" class="map day-map"></div></div>${route?`<div class="actions route-actions"><a class="btn" target="_blank" rel="noopener" href="${route}">🧭 Abrir ruta del día en Google Maps</a></div>`:`<div class="callout compact"><strong>Ruta del día</strong>Este día combina desplazamientos urbanos, traslado al aeropuerto y vuelo; no se representa como una única ruta de carretera.</div>`}<div class="section-title"><h2>Horario</h2></div><div class="card schedule">${d.schedule.map(r=>`<div class="schedule-row"><div class="time">${r[0]}</div><div>${r[1]}</div></div>`).join('')}</div><div class="section-title"><div><h2>Lugares</h2></div><p>Resumen para la jornada. Las fichas ampliadas permiten leer con más calma antes de llegar.</p></div>${d.places.map(p=>{const det=detailFor(p[0]);return `<article class="card place"><h3>${p[0]}</h3><p>${p[1]}</p><div class="actions">${det?`<a class="btn" href="#lugar-${slugify(p[0])}">Leer más →</a>`:''}<a class="btn secondary" target="_blank" rel="noopener" href="${mapsLink(p[0])}">📍 Abrir en Maps</a></div></article>`}).join('')}<div class="callout"><strong>Cinco minutos antes de llegar</strong>${d.before}</div><div class="callout"><strong>Si solo pudiera recomendar una cosa de hoy…</strong>${d.recommend}</div><div class="actions"><a class="btn secondary" href="#dia-${Math.max(1,n-1)}">← Día anterior</a><a class="btn" href="#dia-${Math.min(8,n+1)}">Día siguiente →</a></div></section>`
}
function renderPlaces(){const entries=Object.entries(PLACE_DETAILS);return `<section class="page-head"><div class="container"><div class="eyebrow">Para leer antes de llegar</div><h1>Lugares del viaje</h1><p>Fichas más amplias para quienes quieran conocer la historia, el paisaje y el contexto de cada parada.</p></div></section><section class="container"><div class="places-index">${entries.map(([slug,p])=>`<a class="card place-index-card" href="#lugar-${slug}"><div class="day-number">${p.country} · Día ${p.day}</div><h3>${p.title}</h3><p>${p.lead}</p><span class="text-link">Leer ficha →</span></a>`).join('')}</div></section>`}
function renderPlace(slug){const p=PLACE_DETAILS[slug]; if(!p)return renderPlaces(); return `<section class="page-head place-head"><div class="container"><a class="back" href="#dia-${p.day}">← Volver al Día ${p.day}</a><div class="eyebrow">${p.country} · Día ${p.day}</div><h1>${p.title}</h1><p>${p.lead}</p><div class="actions"><a class="btn" target="_blank" rel="noopener" href="${mapsLink(p.title)}">📍 Abrir en Maps</a></div></div></section><section class="container reading">${p.sections.map(s=>`<article class="card reading-section"><h2>${s[0]}</h2><p>${s[1]}</p></article>`).join('')}<div class="actions"><a class="btn secondary" href="#dia-${p.day}">← Volver a la jornada</a><a class="btn" href="#lugares">Todas las fichas</a></div></section>`}
function historyBlock(key){const h=HISTORY[key];return `<article class="history-block"><div class="day-number">${key==='scotland'?'Escocia':'Irlanda'}</div><h2>${h.title}</h2><p class="history-intro">${h.intro}</p>${h.sections.map(s=>`<section class="card history-section"><h3>${s[0]}</h3><p>${s[1]}</p></section>`).join('')}</article>`}
function renderHistory(){return `<section class="page-head"><div class="container"><div class="eyebrow">Contexto</div><h1>Historia para entender el viaje</h1><p>No es un manual de historia: son las claves necesarias para que castillos, ciudades y paisajes tengan más sentido cuando estemos allí.</p></div></section><section class="container history-wrap">${historyBlock('scotland')}${historyBlock('ireland')}</section>`}
function renderHotels(){return `<section class="page-head"><div class="container"><div class="eyebrow">Alojamiento</div><h1>Hoteles</h1><p>Información de consulta rápida durante el viaje.</p></div></section><section class="container" id="hoteles"><div class="grid">${HOTELS.map(h=>`<article class="card hotel-card"><div class="day-number">${h.city}</div><h3>${h.name}</h3><div class="hotel-meta"><div>${h.address}</div><div><strong>Noches:</strong> ${h.nights}</div>${h.phone?`<div><strong>Tel.</strong> ${h.phone}</div>`:''}${h.email?`<div><strong>Email.</strong> ${h.email}</div>`:''}<div class="hotel-note">${h.note}</div></div><div class="actions"><a class="btn" target="_blank" rel="noopener" href="${mapsLink(h.name+' '+h.address)}">📍 Maps</a>${h.phone?`<a class="btn secondary" href="tel:${h.phone.replace(/\s/g,'')}">☎ Llamar</a>`:''}</div></article>`).join('')}</div></section>`}
function renderPractical(){return `<section class="page-head"><div class="container"><div class="eyebrow">Consulta rápida</div><h1>Información práctica</h1><p>Lo esencial para tener a mano sin abrir el documento Word.</p></div></section><section class="container" id="practico"><div class="quick-list">${practical.map(p=>`<div class="quick-item"><strong>${p[0]}</strong><div class="muted">${p[1]}</div></div>`).join('')}</div></section>`}
function baseMap(id){if(typeof L==='undefined')return null;return L.map(id,{scrollWheelZoom:false})}
function addTiles(m){L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(m)}
function initTripMap(){const el=document.getElementById('tripMap');if(!el||el._leaflet_id)return;const m=baseMap('tripMap');if(!m)return;addTiles(m);const pts=[[55.9533,-3.1883],[56.6826,-5.1023],[57.4778,-4.2247],[56.945,-2.197],[56.3398,-2.7967],[51.8985,-8.4756],[51.9668,-9.5931],[51.8507,-8.294],[53.2707,-9.0568],[52.9715,-9.4309],[53.3498,-6.2603]];L.polyline(pts,{color:'#b88b4a',weight:3,opacity:.8,dashArray:'8 8'}).addTo(m);[['Edimburgo',55.9533,-3.1883],['Cork',51.8985,-8.4756],['Galway',53.2707,-9.0568],['Dublín',53.3498,-6.2603]].forEach(p=>L.marker([p[1],p[2]]).addTo(m).bindPopup(`<strong>${p[0]}</strong>`));m.fitBounds(pts,{padding:[25,25]})}
function initDayMap(n){const el=document.getElementById('dayMap');if(!el||el._leaflet_id)return;const data=DAY_POINTS[n]||[],m=baseMap('dayMap');if(!m)return;addTiles(m);const pts=data.map(p=>[p[1],p[2]]);L.polyline(pts,{color:'#b88b4a',weight:4,opacity:.9}).addTo(m);data.forEach((p,i)=>L.marker([p[1],p[2]]).addTo(m).bindPopup(`<strong>${i+1}. ${p[0]}</strong>`));m.fitBounds(pts,{padding:[25,25]})}
function renderCredits(){const uniq=Object.values(PHOTOS).filter((x,i,a)=>a.findIndex(y=>y.source===x.source)===i);return `<section class="page-head"><div class="container"><div class="eyebrow">Imágenes y cartografía</div><h1>Créditos</h1><p>Fotografías de Wikimedia Commons y mapas de OpenStreetMap.</p></div></section><section class="container"><div class="grid">${uniq.map(p=>`<article class="card credit-card"><img src="${p.url}" alt="${p.caption}" loading="lazy"><h3>${p.caption}</h3><p class="muted">${p.credit}</p><a class="btn secondary" target="_blank" href="${p.source}">Ver ficha y licencia</a></article>`).join('')}</div><div class="callout"><strong>Cartografía</strong>Leaflet + OpenStreetMap. Las líneas de ruta son orientativas; para navegación real, usar Google Maps.</div></section>`}
function router(){let h=location.hash||'#inicio';document.getElementById('mainNav').classList.remove('open');if(h.startsWith('#dia-')){const n=Number(h.split('-')[1]);document.getElementById('app').innerHTML=renderDay(n);setTimeout(()=>initDayMap(n),50);}else if(h==='#dias'){document.getElementById('app').innerHTML=renderHome();setTimeout(()=>{initTripMap();document.getElementById('dias')?.scrollIntoView();},50);}else if(h.startsWith('#lugar-')){document.getElementById('app').innerHTML=renderPlace(h.slice(7));}else if(h==='#lugares'){document.getElementById('app').innerHTML=renderPlaces();}else if(h==='#historia'){document.getElementById('app').innerHTML=renderHistory();}else if(h==='#hoteles'){document.getElementById('app').innerHTML=renderHotels();}else if(h==='#practico'){document.getElementById('app').innerHTML=renderPractical();}else if(h==='#creditos'){document.getElementById('app').innerHTML=renderCredits();}else{document.getElementById('app').innerHTML=renderHome();setTimeout(initTripMap,50);}window.scrollTo(0,0)}
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));
window.addEventListener('hashchange',router);router();