const DAYS = [
 {n:1,date:'Jue 13 ago',title:'Edimburgo',subtitle:'Llegada y Castillo de Edimburgo',sleep:'Edimburgo',tags:['Castillo','Royal Mile','Old Town'],summary:'Primer contacto con la capital escocesa. El día gira alrededor de la visita reservada al Castillo de Edimburgo a las 15:30, dejando el resto de la jornada deliberadamente flexible.',schedule:[['03:00','Salida de Salobreña hacia el aeropuerto de Málaga.'],['06:10','Vuelo Málaga–Edimburgo.'],['08:30','Llegada prevista a Edimburgo.'],['Mañana','Traslado al Holiday Inn Edinburgh y depósito del equipaje.'],['13:00','Comida sencilla cerca del centro o del castillo.'],['14:45','Reunión en la explanada del castillo.'],['15:30','Visita al Castillo de Edimburgo.'],['Tarde','Castlehill, Royal Mile, Victoria Street o Grassmarket.'],['Noche','Cena y descanso.']],places:[['Edimburgo','Edimburgo se entiende mejor como una ciudad construida en capas. La Old Town creció sobre una cresta rocosa que une Castle Rock con Holyrood; de ese eje surgieron la Royal Mile y una red de closes y wynds que descienden por las laderas. En el siglo XVIII, la New Town ofreció el contraste: calles regulares, plazas, jardines y arquitectura georgiana. La coexistencia de ambas ciudades explica buena parte de su personalidad.'],['Castillo de Edimburgo','La fortaleza ocupa Castle Rock, resto resistente de un antiguo sistema volcánico. Fue residencia real, plaza militar, prisión y símbolo del poder escocés. Dentro se superponen siglos de historia: la capilla de Santa Margarita, el Great Hall, las baterías y las Honours of Scotland.'],['Royal Mile','No es una sola calle, sino una sucesión de tramos —Castlehill, Lawnmarket, High Street y Canongate— que conectan el castillo y Holyrood. Entre ambos se concentran St Giles, edificios institucionales, antiguas casas nobles, patios y pasadizos.'],['Victoria Street y Grassmarket','Victoria Street salva con una curva muy característica el fuerte desnivel entre George IV Bridge y Grassmarket. Este último fue mercado y lugar de ejecuciones públicas; hoy ofrece una de las vistas más potentes del castillo sobre los tejados.']],before:'Edimburgo se entiende mejor mirando el relieve. La ciudad medieval creció donde la roca y las pendientes ofrecían defensa; la ciudad georgiana se diseñó siglos después como una respuesta ordenada, luminosa y racional a la densidad de la Old Town.',recommend:'Al salir del castillo, deteneos un momento en Castlehill y mirad hacia la ciudad antes de seguir bajando.'},
 {n:2,date:'Vie 14 ago',title:'Highlands y Lago Ness',subtitle:'Glen Coe, Fort Augustus, Inverness y Pitlochry',sleep:'Edimburgo',tags:['Tour privado','Highlands','Lago Ness'],summary:'Una jornada completa hacia las Highlands, donde paisaje, geología e historia de los clanes se mezclan de forma especialmente intensa.',schedule:[['07:00','Recogida en el Holiday Inn Edinburgh.'],['Mañana','Parada de café y vacas Highland.'],['Mañana','Glen Coe y paradas paisajísticas.'],['13:00 aprox.','Fort Augustus: comida y crucero opcional.'],['Tarde','Lago Ness e Inverness.'],['Regreso','Parada breve en Pitlochry.'],['20:00','Llegada prevista a Edimburgo.']],places:[['Glen Coe','El dramatismo del valle no procede solo de la altura de las montañas. El paisaje se desarrolló sobre rocas asociadas a una gran actividad volcánica antigua y fue remodelado después por los glaciares, que ensancharon el fondo y cortaron las laderas. También está ligado a la matanza de los MacDonald de 1692, uno de los episodios más recordados de la historia de las Highlands.'],['Fort Augustus','En el extremo sur del Lago Ness, Fort Augustus permite observar las esclusas del Canal de Caledonia, una obra del siglo XIX que enlaza varios lagos naturales a través del Great Glen. Para quien no haga el crucero, el paseo junto a las esclusas es una alternativa excelente.'],['Lago Ness','Más allá de la leyenda de Nessie, el lago forma parte de una profunda fractura geológica que atraviesa Escocia de costa a costa. Sus aguas oscuras y sus laderas largas ayudan a entender la escala del Great Glen.'],['Inverness','Capital de las Highlands y centro natural del norte escocés. El paseo junto al río Ness permite una primera impresión breve y agradable de la ciudad.'],['Pitlochry','Última pausa antes de volver a Edimburgo: baños, bebida y recuento general.']],before:'En Glen Coe, paisaje e historia están inseparablemente unidos: un valle modelado por hielo y volcanismo antiguo que conserva además la memoria de uno de los episodios más conocidos de la historia de los clanes.',recommend:'En Glen Coe, dedica unos segundos a mirar el valle sin cámara. La escala del paisaje se entiende mejor así.'},
 {n:3,date:'Sáb 15 ago',title:'Dunnottar y Saint Andrews',subtitle:'Falkland, Stonehaven, Dundee y costa oriental',sleep:'Edimburgo',tags:['Dunnottar','Saint Andrews','Costa'],summary:'La jornada recorre la costa oriental de Escocia. Dunnottar y Saint Andrews son las prioridades claras; Dundee y Queensferry quedan condicionadas al tiempo disponible.',schedule:[['08:00','Recogida en el hotel.'],['Mañana','Falkland.'],['Mediodía','Stonehaven y miradores.'],['Mediodía','Castillo de Dunnottar.'],['Tarde','Dundee si el horario lo permite.'],['Tarde','Saint Andrews.'],['Regreso','South Queensferry si queda margen.'],['19:00','Regreso previsto a Edimburgo.']],places:[['Falkland','Pequeño pueblo de Fife con un centro histórico bien conservado. Es una parada cómoda para café y paseo; quienes conozcan Outlander reconocerán algunos escenarios.'],['Dunnottar','Las ruinas se levantan sobre un promontorio rocoso casi aislado por acantilados. Su posición era una defensa natural extraordinaria. En el siglo XVII protegió las Honours of Scotland —corona, cetro y espada de Estado— frente a las tropas de Oliver Cromwell.'],['Saint Andrews','Reúne tres identidades: antigua capital religiosa de Escocia, sede de la universidad más antigua del país y referencia mundial del golf. Las ruinas de la catedral hablan de su peso medieval; la universidad se mezcla con las calles; y el Old Course ocupa terrenos de dunas junto al mar.'],['Old Course y West Sands','Aunque nadie juegue al golf, merece la pena acercarse al entorno del hoyo 18 y al puente de piedra. West Sands prolonga el paisaje costero y ayuda a entender por qué el golf nació aquí como un deporte ligado al terreno natural.']],before:'Dunnottar reúne tres elementos difíciles de separar: historia, roca y mar. El promontorio explica por sí solo por qué la fortaleza fue tan difícil de conquistar.',recommend:'Caminad al menos hasta el primer mirador de Dunnottar: allí se entiende la escala completa del lugar.'},
 {n:4,date:'Dom 16 ago',title:'Edimburgo y vuelo a Cork',subtitle:'Última mañana en Escocia y llegada a Irlanda',sleep:'Cork',tags:['Vuelo 19:55','Cork','5 coches'],summary:'Mañana flexible en Edimburgo y vuelo nocturno a Cork. La prioridad real es cambiar de país con margen, recoger los cinco coches y llegar tranquilos al hotel.',schedule:[['Mañana','Desayuno, check-out y depósito de equipaje.'],['10:00 aprox.','Misa católica (por confirmar).'],['11:15–14:30','Paseo flexible por Edimburgo.'],['14:30','Comida ligera.'],['16:00','Recogida de equipaje.'],['16:30–17:00','Salida hacia el aeropuerto.'],['19:55','Vuelo Edimburgo–Cork.'],['21:15','Llegada prevista a Cork.'],['Noche','Recogida de cinco coches y traslado al Clayton Hotel Cork City.']],places:[['Dean Village y Water of Leith','Un paseo muy distinto de la Old Town: antiguos molinos, puentes y viviendas encajadas en el valle del Water of Leith. Es una buena opción si el tiempo acompaña.'],['National Museum of Scotland','Una alternativa excelente con lluvia y apta para edades muy distintas. Sus colecciones recorren historia natural, ciencia, tecnología y cultura escocesa.'],['New Town y Princes Street Gardens','La New Town permite ver el proyecto urbano de la Ilustración. Princes Street Gardens ocupan parte del espacio del antiguo Nor Loch, drenado para permitir la expansión de la ciudad.'],['Llegada a Irlanda','Será el primer contacto con la conducción por la izquierda. Los cinco coches deben poder completar la ruta de forma autónoma y conviene asignar conductores, pasajeros y equipaje antes de salir del aeropuerto.']],before:'La mañana debe ser deliberadamente ligera. El éxito del día no será añadir un monumento más, sino llegar a Irlanda con todo el grupo, el equipaje y los cinco coches bien organizados.',recommend:'No añadáis una visita más si compromete el traslado al aeropuerto.'},
 {n:5,date:'Lun 17 ago',title:'Anillo de Kerry y Cobh',subtitle:'Killarney, Ladies\' View, Moll\'s Gap, Kenmare, Sneem, Cahersiveen y tarde en Cobh',sleep:'Cork',tags:['Kerry','Cobh','Cena en Cobh'],summary:'Salida a las 08:00 desde Cork para recorrer en nuestros cinco coches una versión concentrada del Anillo de Kerry. Pasaremos por Killarney, Ladies\' View, Moll\'s Gap, Kenmare, Sneem y Cahersiveen, regresando después hacia Killarney y continuando a Cobh. El objetivo es estar en Cobh alrededor de las 15:00 para dedicar la tarde a la ciudad y cenar allí. Es una jornada exigente: habrá que tratar varias paradas como miradores breves y vigilar el horario.',schedule:[['08:00','Salida desde el Clayton Hotel Cork City.'],['09:20 aprox.','Killarney y entrada en el paisaje del parque nacional.'],['09:40','Ladies\' View y Moll\'s Gap: paradas panorámicas breves.'],['10:15','Kenmare.'],['10:45','Sneem.'],['11:30–12:00','Continuación hacia Cahersiveen.'],['12:00 aprox.','Cahersiveen y regreso hacia Killarney.'],['13:15 aprox.','Paso por Killarney y continuación hacia Cobh.'],['15:00 aprox.','Llegada a Cobh.'],['Tarde','Puerto, catedral de St Colman y Titanic Experience si encaja con la reserva.'],['Noche','Cena en Cobh y regreso al Clayton Hotel Cork City.']],places:[['Anillo de Kerry','La península de Iveragh reúne montañas, lagos glaciares, turberas y una costa atlántica muy recortada. La carretera es parte esencial de la visita: cada tramo cambia la relación entre relieve, agua y mar.'],['Killarney National Park','El parque protege lagos, bosques antiguos y montañas modeladas por los glaciares. Es uno de los paisajes clásicos de Irlanda y el mejor prólogo para la ruta.'],['Ladies\' View','Un mirador privilegiado sobre los lagos de Killarney. Su nombre se relaciona con las damas de compañía de la reina Victoria durante la visita real de 1861.'],['Moll\'s Gap','Paso de montaña entre Killarney y Kenmare, con un paisaje más desnudo y áspero que el de los lagos.'],['Kenmare','Pequeña localidad de fachadas coloridas situada entre las penínsulas de Iveragh y Beara. En nuestro horario será una parada corta.'],['Sneem','Pueblo dividido por el río Sneem, con pequeñas plazas y casas de colores.'],['Cahersiveen','Punto más occidental de nuestra ruta del día, ligado a Daniel O\'Connell y rodeado de un paisaje plenamente atlántico.'],['Cobh','La tarde cambia de tono: del paisaje de Kerry pasamos a un puerto marcado por la emigración, el Titanic, el Lusitania y una poderosa memoria de despedidas.']],before:'El Anillo de Kerry no es una lista de monumentos, sino un paisaje que se va leyendo desde la carretera. Hoy el horario es especialmente exigente: la prioridad es disfrutar algunos puntos clave y llegar a Cobh con tiempo suficiente para pasearlo y cenar allí.',recommend:'Si la ruta se retrasa, recortad paradas antes que convertir el regreso en una carrera. La tarde de Cobh merece algo de margen.'},
 {n:6,date:'Mar 18 ago',title:'Blarney, Limerick, Bunratty y Galway',subtitle:'Castillos, Folk Park y traslado al oeste',sleep:'Galway',tags:['Blarney','Limerick','Bunratty'],summary:'Después del check-out en Cork, visitaremos Blarney Castle & Gardens, continuaremos hasta Limerick para centrarnos en King John\'s Castle y después iremos a Bunratty Castle & Folk Park. La última entrada en Bunratty es a las 16:00, por lo que esa hora debe gobernar la jornada. Desde Bunratty seguiremos a Galway y, si queda tiempo y energía, podremos dar un primer paseo por el centro.',schedule:[['Mañana','Desayuno, check-out y carga de equipaje en los cinco coches.'],['08:30 aprox.','Salida hacia Blarney Castle & Gardens.'],['09:00–11:15','Blarney Castle & Gardens.'],['11:15','Salida hacia Limerick.'],['12:45 aprox.','Llegada a Limerick.'],['13:00–14:00','King John\'s Castle.'],['14:00','Salida hacia Bunratty.'],['14:30–15:00','Llegada a Bunratty Castle & Folk Park.'],['Antes de 16:00','Acceso al recinto; última entrada prevista a las 16:00.'],['17:00 aprox.','Salida hacia Galway.'],['18:15–19:00','Llegada estimada al Maldron Hotel Sandy Road Galway.'],['Noche','Si queda margen: primer paseo por Galway.']],places:[['Blarney Castle','Una gran casa-torre del siglo XV vinculada a los MacCarthy. La Piedra de Blarney es su tradición más célebre, pero la arquitectura y los jardines justifican por sí solos la visita.'],['King John\'s Castle','La gran fortaleza de Limerick domina King\'s Island y el río Shannon. Su origen normando y su papel en los asedios del siglo XVII explican buena parte de la importancia estratégica de la ciudad.'],['Bunratty Castle & Folk Park','Bunratty combina un gran castillo del siglo XV con un parque etnográfico que recrea viviendas, tiendas y edificios de la Irlanda de los siglos XIX y principios del XX.'],['Galway','Llegaremos al final del día. Si el horario acompaña, un paseo por Eyre Square y las calles peatonales será una buena primera toma de contacto.']],before:'Hoy recorremos varias capas de la historia irlandesa: una fortaleza gaélica en Blarney, una ciudad de raíces vikingas y normandas en Limerick, una gran residencia fortificada en Bunratty y, finalmente, Galway, puerta del oeste atlántico.',recommend:'La hora que manda es la última entrada de Bunratty a las 16:00. Si Blarney o Limerick se alargan, recortad allí antes que perder Bunratty.'},
 {n:7,date:'Mié 19 ago',title:'Acantilados de Moher y Galway',subtitle:'Atlántico por la mañana y ciudad el resto del día',sleep:'Galway',tags:['Moher','Galway','Costa oeste'],summary:'Invertimos el orden anterior: primero iremos a los acantilados de Moher, aprovechando la mañana para la gran visita paisajística. Después regresaremos a Galway y dedicaremos el resto de la jornada a recorrer la ciudad sin la presión de tener que salir hacia otra visita.',schedule:[['08:00 aprox.','Salida desde el Maldron Hotel Sandy Road Galway.'],['09:30 aprox.','Llegada a Cliffs of Moher.'],['09:30–11:30','Miradores y centro de visitantes.'],['11:30','Salida hacia Galway; posible tramo por el Burren según horario y condiciones.'],['13:00 aprox.','Llegada a Galway y comida.'],['Tarde','Eyre Square, Shop Street, Lynch\'s Castle, St Nicholas, Quay Street y Spanish Arch.'],['Tarde','Paseo hacia el Corrib, Claddagh o la catedral según ganas y tiempo.'],['Noche','Cena y ambiente de Galway.']],places:[['Acantilados de Moher','Una pared de estratos de arenisca, limos y lutitas frente al Atlántico. Más que la altura, impresionan la continuidad de la costa, el viento y la luz cambiante.'],['El Burren','Si el horario lo permite, parte del regreso puede servir para observar este paisaje kárstico de calizas desnudas, muros de piedra seca y flora sorprendente.'],['Galway','La tarde completa permitirá conocer la ciudad a otro ritmo: su pasado de puerto medieval, las Tribes of Galway, las calles peatonales, la música y su relación constante con el Corrib y la bahía.'],['Latin Quarter y Quay Street','El corazón más animado de la ciudad, con edificios históricos, pubs, tiendas y músicos callejeros.'],['Spanish Arch y Claddagh','El Spanish Arch recuerda el antiguo frente portuario; al otro lado del río estuvo Claddagh, la comunidad pesquera vinculada al famoso anillo.']],before:'Empezar por Moher permite disfrutar el gran paisaje atlántico con la cabeza fresca y dejar para después una tarde urbana flexible. Galway se disfruta mejor caminando que siguiendo una lista rígida.',recommend:'En Moher, guardad el teléfono un minuto. En Galway, reservad un rato sin programa para dejar que cada familia se pierda un poco por las calles.'},
 {n:8,date:'Jue 20 ago',title:'Dublín y regreso',subtitle:'Un paseo breve antes del aeropuerto',sleep:'Casa',tags:['Dublín','Vuelo 15:30','Regreso'],summary:'Desde Galway a Dublín con poco margen. El paseo por la capital es opcional y debe cancelarse si compromete la llegada al aeropuerto.',schedule:[['06:45','Desayuno, check-out y carga de coches en Galway.'],['07:15','Salida hacia Dublín.'],['09:45 aprox.','Llegada a un aparcamiento céntrico, solo si el tráfico lo permite.'],['10:00–11:15','Paseo breve: Christ Church, Dublin Castle, Dame Street y borde de Temple Bar.'],['11:15','Salida hacia el aeropuerto.'],['12:00','Repostaje y devolución de los cinco coches.'],['13:00','Grupo reunido en la terminal.'],['15:30','Vuelo Dublín–Málaga.'],['19:30','Llegada prevista a Málaga.']],places:[['Christ Church y Dublin Castle','El recorrido permite atravesar distintas capas de la historia de Dublín: Christ Church recuerda la ciudad medieval y Dublin Castle fue durante siglos el centro del poder inglés y británico en Irlanda.'],['Temple Bar','Más allá de los pubs más concurridos, conserva una trama de calles estrechas con espacios culturales, librerías, salas de música y pequeños comercios. A primera hora se recorre con más tranquilidad.'],['Dublín literario','Jonathan Swift, Oscar Wilde, W. B. Yeats, James Joyce y Samuel Beckett están vinculados a la ciudad. La literatura, el teatro y la conversación forman parte de su identidad tanto como los monumentos.'],['Orígenes de la ciudad','Dublín creció a partir de núcleos gaélicos y vikingos. El nombre inglés procede de Dubh Linn, “laguna negra”, y el nombre irlandés, Baile Átha Cliath, recuerda un antiguo vado del Liffey.'],['Trinity College','Si en otro viaje hubiera más tiempo, Trinity College y el Book of Kells serían dos referencias fundamentales. En esta ocasión, la breve visita debe centrarse en el corazón histórico y en llegar al aeropuerto sin tensión.']],before:'No vais a conocer Dublín en una hora. Pero sí podéis cruzar algunas de sus capas históricas, llevaros una primera impresión y cerrar el viaje con calma.',recommend:'Si a las 09:45 no estáis aparcando en el centro, id directamente al aeropuerto.'}
];

const DAY_POINTS={1:[["Holiday Inn Edinburgh",55.9429,-3.272],["Edinburgh Castle",55.9486,-3.1999],["Royal Mile",55.95,-3.187],["Grassmarket",55.9473,-3.1954]],2:[["Edinburgh",55.9533,-3.1883],["Glen Coe",56.6826,-5.1023],["Fort Augustus",57.144,-4.68],["Loch Ness",57.3229,-4.4244],["Inverness",57.4778,-4.2247],["Pitlochry",56.702,-3.734]],3:[["Edinburgh",55.9533,-3.1883],["Falkland",56.252,-3.206],["Dunnottar Castle",56.945,-2.197],["Dundee",56.462,-2.9707],["Saint Andrews",56.3398,-2.7967]],4:[["Edinburgh",55.9533,-3.1883],["Edinburgh Airport",55.9508,-3.3615],["Cork Airport",51.8413,-8.4911],["Clayton Hotel Cork City",51.8992,-8.464]],5:[["Cork",51.8985,-8.4756],["Killarney",52.0599,-9.5044],["Ladies View",51.9668,-9.5931],["Moll's Gap",51.932,-9.659],["Kenmare",51.88,-9.583],["Sneem",51.838,-9.9],["Cahersiveen",51.948,-10.225],["Killarney",52.0599,-9.5044],["Cobh",51.8507,-8.294]],6:[["Clayton Hotel Cork City",51.8992,-8.464],["Blarney Castle",51.9291,-8.5706],["King John's Castle Limerick",52.668,-8.625],["Bunratty Castle",52.6965,-8.8156],["Galway",53.2707,-9.0568]],7:[["Galway",53.2707,-9.0568],["Cliffs of Moher",52.9715,-9.4309],["Galway",53.2707,-9.0568]],8:[["Galway",53.2707,-9.0568],["Dublin Castle",53.3429,-6.2675],["Dublin Airport",53.4264,-6.2499]]};
const PHOTOS={1:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Edinburgh%20panorama%20from%20the%20castle.jpg?width=1800",caption:"Edimburgo desde el castillo",credit:"Chinnie666 · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Edinburgh_panorama_from_the_castle.jpg"},2:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Glencoe%2C%20Scotland%2C%20UK.jpg?width=1600",caption:"Glen Coe",credit:"Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Glencoe,_Scotland,_UK.jpg"},3:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Dunnottar%20Castle%20%28Scotland%29.jpg?width=1600",caption:"Dunnottar",credit:"Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Dunnottar_Castle_(Scotland).jpg"},4:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Edinburgh%20panorama%20from%20the%20castle.jpg?width=1800",caption:"Edimburgo",credit:"Chinnie666 · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Edinburgh_panorama_from_the_castle.jpg"},5:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Ladies%20view%20killarney.jpg?width=1600",caption:"Ladies View",credit:"Ianmoran87 · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Ladies_view_killarney.jpg"},6:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Cobh%20Harbour%20Cathedral.jpg?width=1400",caption:"Cobh",credit:"Kondephy · Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Cobh_Harbour_Cathedral.jpg"},7:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Cliffs%20of%20Moher%2C%20Ireland.JPG?width=1600",caption:"Cliffs of Moher",credit:"Jac31 · Wikimedia Commons",source:"https://commons.wikimedia.org/wiki/File:Cliffs_of_Moher,_Ireland.JPG"},8:{url:"https://commons.wikimedia.org/wiki/Special:FilePath/Dublin%20Castle.jpg?width=1600",caption:"Dublin Castle",credit:"Mike Peel · CC BY-SA 4.0",source:"https://commons.wikimedia.org/wiki/File:Dublin_Castle.jpg"}};

const HOTELS = [
 {city:'Edimburgo',name:'Holiday Inn Edinburgh',address:'132 Corstorphine Road, Edinburgh',nights:'13, 14 y 15 de agosto',phone:'',email:'',note:'Base durante los tres primeros días en Escocia.'},
 {city:'Cork',name:'Clayton Hotel Cork City',address:'Lapps Quay, Cork, Co. Cork, Irlanda',nights:'16 y 17 de agosto',phone:'+353 21 422 4900',email:'res.corkcity@claytonhotels.com',note:'Check-in 16:00 · check-out 12:00. El bono indica que no dispone de aparcamiento privado; hay aparcamiento público en Lapps Quay con tarifa reducida para residentes hasta las 12:00 del día de salida.'},
 {city:'Galway',name:'Maldron Hotel Sandy Road Galway',address:'Headford Point, Headford Road, Galway City, Co. Galway, H91 ET6N, Irlanda',nights:'18 y 19 de agosto',phone:'+353 91 513 200',email:'reservations.sandyroad@maldronhotels.com',note:'Check-in 16:00 · check-out 12:00. El bono indica aparcamiento disponible con posibles cargos adicionales y Wi‑Fi incluido.'}
];

const HISTORY = {
 scotland:{title:'Comprender Escocia: historia para leer el paisaje',intro:'Escocia se entiende mejor cuando historia y geografía se leen juntas. Castillos en rocas casi inexpugnables, ciudades construidas junto a estuarios, valles que durante siglos fueron rutas naturales y Highlands de comunicaciones difíciles forman parte de un mismo relato. Estas claves ayudan a que Edimburgo, Glen Coe, Dunnottar o Saint Andrews dejen de ser visitas aisladas.',sections:[
 ['La geología antes que la historia','Gran parte del relieve escocés es muchísimo más antiguo que cualquier reino. Antiguos choques continentales, episodios volcánicos, fallas y, finalmente, las glaciaciones dieron forma a las Highlands, al Great Glen y a numerosos lagos. Castle Rock en Edimburgo es el resto de un antiguo sistema volcánico; Glen Coe conserva huellas de volcanismo y hielo; Loch Ness ocupa una profunda línea de fractura. El terreno condicionó defensas, agricultura y comunicaciones.'],
 ['Pictos, gaélicos y romanos','Roma conquistó gran parte de Britania, pero el norte nunca quedó incorporado de forma estable al Imperio. Tras la etapa romana convivieron varios mundos: pictos en buena parte del norte y este, gaélicos de Dál Riata en el oeste, britanos en Strathclyde y anglos en el sureste. Escocia no apareció de repente: fue el resultado de siglos de alianzas, guerras y mezclas entre esos pueblos.'],
 ['El reino de Alba','Desde el siglo IX fue tomando forma el reino de Alba, núcleo de la futura Escocia. Su expansión fue gradual y la autoridad real nunca tuvo la misma fuerza en todo el territorio. Las islas y las costas occidentales mantuvieron vínculos nórdicos y gaélicos, mientras las tierras del sur y el este se integraban cada vez más en redes europeas de comercio, monasterios y ciudades.'],
 ['Wallace y Robert the Bruce','La muerte de Alejandro III y la crisis sucesoria del siglo XIII permitieron a Eduardo I de Inglaterra intervenir en Escocia. William Wallace se convirtió en símbolo de resistencia tras Stirling Bridge en 1297. Robert the Bruce construyó después una posición política mucho más sólida y fue coronado rey en 1306. La victoria de Bannockburn en 1314 fue decisiva para consolidar la independencia del reino.'],
 ['Los Estuardo y María Estuardo','La dinastía Stewart gobernó Escocia desde el siglo XIV. María Estuardo es su figura más famosa: reina desde la infancia, educada en Francia, regresó a una Escocia transformada por la Reforma. Su reinado terminó en abdicación y huida a Inglaterra; fue ejecutada en 1587. Su hijo Jacobo VI acabaría heredando también el trono inglés.'],
 ['La Reforma','En 1560 la Reforma escocesa rompió con Roma y consolidó una Iglesia de tradición presbiteriana. El cambio alteró religión, educación y cultura política. Las ruinas de la catedral de Saint Andrews permiten visualizar físicamente esa ruptura: un centro que había dominado la vida religiosa medieval perdió su función en pocas décadas.'],
 ['1603 y 1707','En 1603 Jacobo VI de Escocia heredó el trono inglés: un mismo monarca gobernó dos reinos que conservaron parlamentos y leyes propios. En 1707 los Actos de Unión crearon el Reino de Gran Bretaña y un Parlamento común en Westminster. Escocia mantuvo, sin embargo, su sistema jurídico, su Iglesia y una fuerte tradición educativa, elementos fundamentales para conservar una identidad institucional propia.'],
 ['Jacobitas y Culloden','Las rebeliones jacobitas intentaron restaurar a la dinastía Estuardo. En 1745 Charles Edward Stuart, Bonnie Prince Charlie, encabezó una campaña que llegó profundamente en Inglaterra antes de retirarse. La derrota de Culloden en 1746 terminó con el último gran levantamiento. Después se intensificó el control de las Highlands y se transformaron muchas estructuras tradicionales.'],
 ['Clanes y Clearances','Los clanes eran redes de parentesco, lealtad y territorio, no simples familias con tartanes. Entre los siglos XVIII y XIX ese mundo cambió radicalmente. Los Highland Clearances desplazaron a numerosas comunidades cuando grandes propiedades se reorganizaron para actividades más rentables. Muchos habitantes emigraron a las ciudades, a las Lowlands o al extranjero.'],
 ['La Ilustración escocesa','Edimburgo y Glasgow vivieron en el siglo XVIII una extraordinaria concentración intelectual. David Hume, Adam Smith, James Hutton, Joseph Black y otros pensadores transformaron filosofía, economía, geología, química y medicina. En pocas décadas Escocia tuvo una influencia mundial desproporcionada respecto a su tamaño.'],
 ['Industria y modernidad','Glasgow se convirtió en potencia industrial y naval; Dundee destacó en la industria y el comercio marítimo; Edimburgo reforzó su papel financiero, administrativo y cultural. Escocia participó activamente en el Imperio británico, una herencia compleja que hoy se estudia también desde sus consecuencias coloniales.'],
 ['La Escocia actual','Desde 1999 Escocia cuenta nuevamente con un Parlamento propio para numerosas competencias. El debate sobre autonomía e independencia continúa, pero para el viajero resulta especialmente visible la convivencia entre pertenencia al Reino Unido y una identidad escocesa muy fuerte, expresada en instituciones, deporte, lengua, música y memoria histórica.']
 ]},
 ireland:{title:'Comprender Irlanda: una historia de continuidad, conquista y emigración',intro:'Irlanda conserva una personalidad histórica muy distinta de Gran Bretaña aunque ambas islas hayan estado profundamente conectadas. Cultura gaélica, monasterios, ciudades vikingas, castillos normandos, dominio inglés, hambruna, emigración e independencia forman capas que veremos en Cobh, Limerick, Bunratty, Galway y Dublín.',sections:[
 ['El mundo gaélico','Durante siglos Irlanda estuvo dividida entre numerosos reinos y dinastías. No existía un Estado nacional unificado, pero la lengua, las leyes y las tradiciones gaélicas crearon una base cultural común muy duradera. El paisaje estaba organizado alrededor de linajes, monasterios y centros de poder regional.'],
 ['Cristianismo y monasterios','El cristianismo se extendió desde el siglo V. San Patricio se convirtió en la figura más famosa, aunque no fue el único misionero. Los monasterios irlandeses se transformaron en importantes centros de estudio y producción artística. Manuscritos como el Book of Kells muestran el extraordinario nivel cultural alcanzado por esas comunidades.'],
 ['Vikingos y ciudades','Desde finales del siglo VIII llegaron incursiones vikingas. Algunos grupos terminaron estableciendo asentamientos permanentes y redes comerciales. Dublín, Waterford, Cork y Limerick tienen raíces urbanas ligadas a esa presencia nórdica. Los vikingos no quedaron separados del mundo irlandés: participaron en su política y acabaron integrándose en buena medida.'],
 ['Los normandos','En 1169 desembarcaron nobles anglonormandos y poco después intervino Enrique II de Inglaterra. Se levantaron castillos y señoríos, pero la conquista fue incompleta. Muchos linajes normandos adoptaron lengua y costumbres gaélicas. Durante siglos coexistieron territorios sometidos a grados muy distintos de control inglés.'],
 ['Reforma, plantaciones y conflicto','Desde el siglo XVI la Corona inglesa trató de imponer un control más directo. La Reforma creó una profunda fractura religiosa: el poder estatal era protestante mientras la mayoría de la población permaneció católica. Confiscaciones y plantaciones, especialmente en Ulster, transformaron la propiedad de la tierra y dejaron consecuencias que duraron siglos.'],
 ['Cromwell y Limerick','Las guerras del siglo XVII fueron especialmente duras. Las campañas de Oliver Cromwell quedaron grabadas en la memoria irlandesa por su violencia y por nuevas confiscaciones. Décadas después, la guerra entre jacobitas y guillermitas terminó con la derrota jacobita y el Tratado de Limerick de 1691, un episodio directamente relacionado con la ciudad que visitaremos.'],
 ['La Gran Hambruna','Entre 1845 y 1852 el tizón destruyó repetidamente la cosecha de patata, base alimentaria de millones de personas pobres. La enfermedad fue el detonante; la estructura agraria, la pobreza y una respuesta insuficiente agravaron la catástrofe. Murió alrededor de un millón de personas y otro millón emigró. La población irlandesa tardó generaciones en recuperarse.'],
 ['Cobh y la emigración','La emigración continuó mucho después de la Hambruna. Cobh, entonces Queenstown, fue una de las grandes puertas de salida hacia Gran Bretaña, Estados Unidos, Canadá y Australia. Su puerto adquiere otro significado cuando se recuerda que para muchas familias fue la última imagen de Irlanda.'],
 ['1916 e independencia','El Levantamiento de Pascua de 1916 fue derrotado, pero la ejecución de sus dirigentes cambió el clima político. Tras la guerra de independencia de 1919-1921, el Tratado Anglo-Irlandés creó el Estado Libre Irlandés. El acuerdo dividió al movimiento nacionalista y desembocó en una guerra civil. Seis condados del noreste permanecieron dentro del Reino Unido como Irlanda del Norte.'],
 ['República y transformación','La República de Irlanda se formalizó en 1949. Durante décadas continuó siendo un país con fuerte emigración, pero la integración europea y las transformaciones económicas y sociales de finales del siglo XX modificaron profundamente su posición. El Acuerdo de Viernes Santo de 1998 creó un marco decisivo para reducir el conflicto en Irlanda del Norte.'],
 ['Una memoria visible','La historia irlandesa no está encerrada en museos. Está en los muelles de Cobh, los castillos de Limerick y Bunratty, las calles de Galway y los edificios políticos de Dublín. Leer esas huellas hace que el viaje sea mucho más rico que una simple sucesión de paisajes verdes y pubs.']
 ]}
};

const practical = [
 ['Documentación','Pasaporte en vigor. ETA del Reino Unido para cada viajero que la necesite, incluidos menores. Tarjeta Sanitaria Europea, seguro de viaje, permisos de conducir y copias digitales de reservas.'],
 ['Equipaje','Capas, impermeable real, calzado cómodo, mochila pequeña por familia, medicación, baterías externas y adaptadores tipo G.'],
 ['Dinero','Escocia utiliza libra esterlina; Irlanda, euro. Conviene pagar en moneda local cuando el terminal ofrezca conversión.'],
 ['Cinco coches','Asignación fija de personas y equipaje. Un conductor principal y uno suplente por coche si el contrato lo permite. Coches A, B, C, D y E.'],
 ['Conducción por la izquierda','En rotondas se circula en sentido horario. Programar destinos antes de iniciar la marcha y usar puntos de reunión concretos, no convoy cerrado.'],
 ['Emergencias','Reino Unido: 999 / 112 · Irlanda: 112 / 999.']
];


const ROUTES = {
  1:{mode:'walking',points:['Holiday Inn Edinburgh','Edinburgh Castle','Royal Mile Edinburgh','Grassmarket Edinburgh']},
  2:{mode:'driving',points:['Edinburgh','Glen Coe Scotland','Fort Augustus','Inverness','Pitlochry','Edinburgh']},
  3:{mode:'driving',points:['Edinburgh','Falkland Fife','Dunnottar Castle','Dundee','St Andrews Scotland','Edinburgh']},
  5:{mode:'driving',points:['Clayton Hotel Cork City','Killarney','Ladies View Killarney','Molls Gap','Kenmare','Sneem','Cahersiveen','Killarney','Cobh']},
  6:{mode:'driving',points:['Clayton Hotel Cork City','Blarney Castle','King Johns Castle Limerick','Bunratty Castle and Folk Park','Maldron Hotel Sandy Road Galway']},
  7:{mode:'driving',points:['Maldron Hotel Sandy Road Galway','Cliffs of Moher','Maldron Hotel Sandy Road Galway']},
  8:{mode:'driving',points:['Maldron Hotel Sandy Road Galway','Dublin Castle','Dublin Airport']}
};

const PLACE_DETAILS = {
 'edimburgo':{title:'Edimburgo',country:'Escocia',day:1,lead:'Una capital construida sobre un relieve extraordinario, donde la ciudad medieval y la gran ampliación georgiana se leen como dos capítulos de una misma historia.',sections:[
  ['Una ciudad nacida de un volcán','Castle Rock es el resto de un antiguo sistema volcánico. Mucho después, los glaciares erosionaron el terreno y dejaron una roca abrupta al oeste con una cresta alargada hacia el este. Sobre esa forma natural se desarrolló la ciudad medieval. La Royal Mile sigue, por tanto, una geografía que existía cientos de millones de años antes que Edimburgo.'],
  ['El castillo y el burgo medieval','La fortaleza convirtió el lugar en un centro político y militar. A sus pies creció un burgo real que se extendió por la cresta hacia Holyrood. Como el espacio útil era muy limitado, la ciudad creció hacia arriba y hacia dentro: edificios altos, patios y closes que descendían por las laderas. Esa densidad todavía se percibe al caminar por la Old Town.'],
  ['La Royal Mile','Castlehill, Lawnmarket, High Street y Canongate forman el eje entre el castillo y Holyroodhouse. En apenas una milla escocesa se concentran St Giles, antiguas casas nobles, edificios públicos y decenas de pasadizos. Caminarla es recorrer físicamente la transición desde la fortaleza a la residencia real.'],
  ['Una ciudad demasiado llena','En los siglos XVII y XVIII la Old Town sufría congestión, incendios y graves problemas sanitarios. Al norte, el Nor Loch había dejado de ser solo una defensa natural y se había convertido en una masa de agua insalubre. La élite urbana empezó a imaginar una expansión que reflejara nuevas ideas de orden, higiene y modernidad.'],
  ['La New Town','El plan de James Craig para la primera New Town fue aprobado en 1767. Calles rectas, plazas, jardines y fachadas georgianas ofrecían un contraste radical con el laberinto medieval. El Nor Loch fue drenado; su antigua depresión terminó ocupada por Princes Street Gardens y el corredor ferroviario. Desde los jardines se entiende perfectamente la enorme diferencia de cota con la Old Town.'],
  ['La Ilustración escocesa','Durante el siglo XVIII Edimburgo fue uno de los grandes centros intelectuales de Europa. David Hume, Adam Smith, James Hutton, Joseph Black y numerosos médicos, abogados y científicos compartían sociedades y debates. La ciudad combinó una escala relativamente pequeña con una concentración extraordinaria de talento y ganó el apodo de “Atenas del Norte”.'],
  ['Una ciudad literaria','Walter Scott contribuyó a construir una imagen romántica de la historia escocesa; Robert Louis Stevenson utilizó la ciudad como paisaje moral y emocional; Arthur Conan Doyle nació aquí y estudió medicina en su universidad. Esa tradición continúa en festivales, librerías y una intensa vida cultural.'],
  ['Qué mirar mientras caminamos','En la Old Town, levantad la vista hacia los edificios y fijaos en cómo los closes bajan desde la cresta. En Princes Street Gardens, mirad el castillo como una pared urbana suspendida sobre el parque. En la New Town, observad la regularidad de fachadas y perspectivas. Edimburgo se disfruta más leyendo esas relaciones que completando una lista de monumentos.'],
  ['Capital actual','Edimburgo es hoy capital política, cultural y administrativa de Escocia. El Parlamento escocés volvió a reunirse en 1999 y ocupa desde 2004 su edificio junto a Holyrood. Festivales, universidades, turismo, finanzas y administración conviven con un patrimonio excepcional que sigue formando parte de una ciudad viva.']
 ]},
 'castillo-de-edimburgo':{title:'Castillo de Edimburgo',country:'Escocia',day:1,lead:'Fortaleza, residencia real y símbolo nacional sobre Castle Rock.',sections:[
  ['Castle Rock','La roca del castillo es el resto resistente de un antiguo complejo volcánico. La erosión y los glaciares eliminaron materiales más blandos y dejaron una posición abrupta por tres lados, con un acceso más fácil desde el este. Esa combinación explica por qué el lugar tuvo un valor defensivo excepcional.'],
  ['Una fortaleza de muchas épocas','El conjunto no responde a un único proyecto. La capilla de Santa Margarita, del siglo XII, es el edificio conservado más antiguo; el Great Hall recuerda la etapa cortesana y real; y baterías, cuarteles y prisiones muestran el uso militar posterior. Recorrer el castillo es recorrer siglos de transformaciones.'],
  ['Las Honours of Scotland y la Stone of Destiny','Las joyas de la Corona escocesa se cuentan entre las insignias reales más antiguas conservadas en Europa. Junto a ellas se muestra la Stone of Destiny, vinculada durante siglos a las ceremonias de coronación de los reyes de Escocia.'],
  ['Qué no perderse','Crown Square, la capilla de Santa Margarita, el Great Hall y las vistas sobre la ciudad justifican la visita incluso si alguna de las zonas interiores tiene cola.']
 ]},
 'glen-coe':{title:'Glen Coe',country:'Escocia',day:2,lead:'Uno de los paisajes más poderosos de las Highlands, donde volcanismo antiguo, glaciaciones y memoria de los clanes se superponen.',sections:[
  ['Volcanes y hielo','Las rocas de Glen Coe están relacionadas con una gran estructura volcánica formada hace cientos de millones de años. Mucho después, los glaciares ocuparon el valle y excavaron su característica sección en U. El fondo relativamente abierto y las laderas que ascienden con brusquedad son algunas de las huellas más claras del trabajo del hielo.'],
  ['Three Sisters y Buachaille Etive Mòr','Las Three Sisters forman parte de la gran ladera de Bidean nam Bian. Buachaille Etive Mòr se alza como una pirámide a la entrada oriental del valle. Son imágenes muy conocidas, pero conviene mirar también cascadas, valles laterales suspendidos y cambios de vegetación, que cuentan la historia geológica del lugar.'],
  ['El mundo de los clanes','Antes de la modernización del Estado, gran parte de las Highlands se organizaba mediante redes de parentesco, jefaturas y lealtades territoriales. Los MacDonald de Glencoe eran una rama de uno de los grandes linajes del oeste. El clan era una estructura social y política, no simplemente una familia identificada por un tartán.'],
  ['La matanza de 1692','Tras la revolución que expulsó a Jacobo VII de Escocia, los jefes de clan debían jurar lealtad a los nuevos monarcas. Alastair MacIain de Glencoe presentó su juramento tarde. Soldados del Gobierno fueron alojados durante casi dos semanas por los MacDonald y recibieron después la orden de atacarlos. Murieron decenas de personas y otras fallecieron al huir en pleno invierno.'],
  ['Por qué el episodio dejó tanta huella','La matanza resultó especialmente escandalosa porque se produjo después de que los soldados hubieran aceptado hospitalidad. Esa ruptura de las normas tradicionales dio al episodio un enorme peso moral y lo convirtió en una de las historias más recordadas de las Highlands.'],
  ['Cuando estéis allí','No busquéis únicamente la foto de las Three Sisters. Observad la forma completa del valle y recordad que este paisaje fue hogar y territorio de pastoreo mucho antes de convertirse en icono turístico. La escala y el silencio son una parte esencial de la experiencia.']
 ]},
 'lago-ness':{title:'Lago Ness',country:'Escocia',day:2,lead:'Un lago célebre por Nessie, pero geológicamente mucho más interesante de lo que su leyenda sugiere.',sections:[
  ['El Great Glen','Loch Ness forma parte del Great Glen, una gran línea de fractura que atraviesa Escocia de suroeste a nordeste. Los glaciares aprovecharon esa debilidad de la corteza y profundizaron el valle, creando una cadena de lagos largos y estrechos.'],
  ['Agua oscura y gran profundidad','El color oscuro del agua se debe en parte a materia orgánica procedente de las turberas. Esa apariencia, combinada con la profundidad del lago y la frecuencia de nieblas, ha contribuido a la atmósfera que rodea las historias sobre el monstruo.'],
  ['Nessie','Los relatos modernos sobre una criatura en el lago adquirieron fama internacional en el siglo XX. No existe evidencia científica que demuestre la presencia de un gran animal desconocido, pero la leyenda se ha convertido en parte inseparable de la cultura popular de las Highlands.']
 ]},
 'dunnottar':{title:'Castillo de Dunnottar',country:'Escocia',day:3,lead:'Una fortaleza espectacular cuyo sistema defensivo más importante era el propio promontorio.',sections:[
  ['Una posición casi inexpugnable','Dunnottar ocupa una plataforma rocosa separada de tierra firme por un acceso estrecho y rodeada por acantilados sobre el Mar del Norte. La topografía permitía defender el lugar con relativamente pocos hombres. Antes de entrar, el primer mirador explica mejor que cualquier plano por qué se eligió esta posición.'],
  ['Siglos de edificios','Las ruinas actuales pertenecen a épocas distintas: fortificación, residencias, capilla, almacenes y dependencias militares. Dunnottar no fue un castillo diseñado de una vez, sino un pequeño conjunto que se transformó durante siglos según cambiaban propietarios, necesidades y técnicas de guerra.'],
  ['Wallace y la memoria medieval','La tradición vincula Dunnottar con William Wallace y las guerras contra Inglaterra a finales del siglo XIII. Como ocurre con muchas historias medievales, hechos y leyenda se mezclaron con el tiempo. Lo importante es recordar que dominar fortalezas como esta era esencial para controlar la costa oriental.'],
  ['Las Honours of Scotland','Ante el avance de las fuerzas de Oliver Cromwell en el siglo XVII, la corona, el cetro y la espada de Estado de Escocia fueron llevados a Dunnottar. Tras un largo asedio, lograron sacarse ocultos y permanecieron escondidos hasta la restauración de la monarquía.'],
  ['La Whigs Vault','Dunnottar conserva también una historia más oscura. En 1685 más de un centenar de Covenanters fueron encerrados en condiciones terribles en una bóveda del castillo. El lugar recuerda que las fortalezas no solo protegían: también servían para imponer poder y castigo.'],
  ['Cuando estéis allí','Quien no quiera bajar todos los escalones puede quedarse en los miradores sin perder la esencia de la visita. Si entráis, intentad imaginar el promontorio lleno de actividad: soldados, sirvientes, almacenes y habitaciones donde hoy solo vemos ruinas.']
 ]},
 'saint-andrews':{title:'Saint Andrews',country:'Escocia',day:3,lead:'Una pequeña ciudad cuya importancia histórica es enorme: gran centro religioso medieval, universidad más antigua de Escocia y capital simbólica del golf.',sections:[
  ['Antes del golf','Saint Andrews fue durante siglos el principal centro eclesiástico de Escocia y destino de peregrinación. La tradición vinculó el lugar a reliquias de san Andrés, que acabaría siendo patrón del país. Esa función religiosa explica la escala de la catedral y la influencia política de la ciudad.'],
  ['La catedral y la Reforma','La gran catedral fue una de las instituciones religiosas más poderosas del reino. La Reforma escocesa de 1560 cambió radicalmente su destino. El enorme recinto en ruinas permite imaginar el peso que tuvo antes de que la nueva Iglesia protestante transformara la vida religiosa.'],
  ['El castillo','El castillo fue residencia de obispos y escenario de conflictos religiosos. Durante un asedio del siglo XVI se excavaron una mina y una contramina, todavía conservadas, que muestran de manera extraordinaria cómo podía desarrollarse la guerra bajo tierra.'],
  ['La universidad','Fundada a comienzos del siglo XV, es la universidad más antigua de Escocia. Sus colegios y patios están integrados en el casco urbano, por lo que la universidad no se visita como un recinto separado: forma parte de la identidad cotidiana de Saint Andrews.'],
  ['Por qué el golf nació aquí','Los links son terrenos arenosos y ondulados junto al mar, poco aptos para la agricultura pero perfectos para un juego que aprovechaba dunas y depresiones naturales. El Old Course evolucionó con el uso y Saint Andrews ayudó después a fijar reglas y tradiciones del golf moderno.'],
  ['Old Course y West Sands','El pequeño Swilcan Bridge junto al hoyo 18 es una imagen universal del golf. West Sands muestra el paisaje costero que explica el origen de los links. Incluso para quien no tenga interés deportivo, merece la pena ver cómo ciudad, universidad y costa se encuentran en pocos minutos a pie.']
 ]},
 'anillo-de-kerry':{title:'Anillo de Kerry',country:'Irlanda',day:5,lead:'Una ruta panorámica por la península de Iveragh donde glaciares, montañas y Atlántico se suceden casi en cada curva.',sections:[
  ['La península de Iveragh','Iveragh está formada por antiguas rocas, especialmente areniscas, que fueron plegadas y elevadas mucho antes de las glaciaciones. Después, el hielo excavó valles y cubetas y el Atlántico recortó la costa. El resultado es un paisaje robusto de montañas, lagos, playas y cabos.'],
  ['Killarney','Los lagos de Killarney, los bosques de roble y tejo y las montañas forman uno de los paisajes más conocidos de Irlanda. La zona alberga además una importante población de ciervo rojo y conserva algunos de los bosques atlánticos más valiosos del país.'],
  ['Ladies View y Moll’s Gap','Ladies View permite contemplar los lagos desde una posición elevada. Moll’s Gap cambia el escenario hacia un paso de montaña más desnudo. En pocos kilómetros se aprecia cómo el paisaje de Kerry varía continuamente.'],
  ['Kenmare, Sneem y Cahersiveen','Kenmare aporta la escala de una pequeña localidad de mercado; Sneem, la imagen de un pueblo de casas de colores junto al río; Cahersiveen marca el sector occidental de nuestro recorrido y está ligado a Daniel O’Connell, gran figura política del siglo XIX.'],
  ['Una mañana muy concentrada','El Ring of Kerry suele ocupar un día completo. Nuestro itinerario lo concentra porque queremos estar en Cobh a las 15:00. Eso obliga a seleccionar: pocas paradas, tiempos cortos y atención constante al reloj. La carretera debe disfrutarse sin intentar convertir cada mirador en una visita.']
 ]},
 'cobh':{title:'Cobh',country:'Irlanda',day:5,lead:'Un puerto de casas de colores cuya historia está marcada por la emigración, el Titanic y el Lusitania.',sections:[
  ['Un gran puerto natural','Cobh se encuentra en Cork Harbour, uno de los mayores puertos naturales del mundo. La protección de la bahía y su profundidad explican su importancia naval y comercial. La localidad creció sobre las laderas de Great Island y parece descender hacia el agua.'],
  ['Queenstown','En 1849, tras una visita de la reina Victoria, la localidad fue rebautizada como Queenstown. Recuperó el nombre Cobh en 1920. Por eso los documentos de la Gran Hambruna, el Titanic y el Lusitania suelen referirse al lugar como Queenstown.'],
  ['La puerta de la emigración','Durante los siglos XIX y XX millones de irlandeses emigraron. Muchos salieron por este puerto, especialmente después de la Gran Hambruna. Para numerosas familias, Cobh fue la última imagen de Irlanda antes de iniciar una vida en Gran Bretaña, Estados Unidos, Canadá o Australia.'],
  ['El Titanic','El Titanic hizo aquí su última escala el 11 de abril de 1912. El gran buque permaneció fondeado y pequeñas embarcaciones trasladaron pasajeros, correo y equipaje. Cuatro días después se hundió en el Atlántico. Saberlo da una dimensión especial al paseo por el mismo puerto desde el que partieron aquellos pasajeros.'],
  ['El Lusitania','En 1915 el transatlántico Lusitania fue torpedeado por un submarino alemán frente a la costa de Cork. Supervivientes y cuerpos fueron llevados a Queenstown. El desastre volvió a situar este puerto en el centro de un acontecimiento internacional y dejó una profunda memoria local.'],
  ['St Colman Cathedral','La catedral católica de St Colman, construida entre los siglos XIX y XX, se alza sobre la ladera con una gran aguja neogótica. El contraste entre el edificio monumental, las calles empinadas y las fachadas de colores forma la imagen más reconocible de Cobh.'],
  ['Una tarde mejor que una visita de paso','El cambio de itinerario beneficia mucho a Cobh. Después de Kerry podremos bajar el ritmo, recorrer el paseo marítimo, subir hacia la catedral y cenar en la ciudad. Es un lugar que gana cuando se dispone de tiempo para mirar el puerto y pensar en su historia.']
 ]},
 'blarney-castle':{title:'Blarney Castle & Gardens',country:'Irlanda',day:6,lead:'Mucho más que la piedra famosa: una gran casa-torre gaélica rodeada de jardines y leyendas.',sections:[
  ['Los MacCarthy','La torre principal fue construida en el siglo XV por los MacCarthy de Muskerry. Como otras tower houses irlandesas, combinaba residencia, representación y defensa. Las escaleras estrechas y los espacios superpuestos recuerdan que la seguridad pesaba tanto como la comodidad.'],
  ['La Piedra de Blarney','La tradición afirma que besar la piedra concede el “gift of the gab”, el don de la elocuencia. Existen varias leyendas sobre su origen y ninguna explicación histórica definitiva. Hoy el ritual forma parte inseparable de la visita, pero no debería eclipsar el propio castillo.'],
  ['Rock Close','Rock Close mezcla árboles, roca, agua y relatos de druidas, brujas y seres del folclore. Muchas asociaciones son románticas y relativamente modernas, pero el lugar ofrece un paseo muy distinto de la subida a la torre.'],
  ['Los jardines','La finca es extensa y cuenta con numerosos senderos y jardines. Nuestro horario obliga a seleccionar: torre y piedra para quien quiera la experiencia clásica; Rock Close y jardines próximos para quienes prefieran una visita más tranquila.']
 ]},
 'king-john-s-castle':{title:'King John\'s Castle',country:'Irlanda',day:6,lead:'Una gran fortaleza normanda sobre el Shannon, clave para comprender la importancia estratégica de Limerick.',sections:[
  ['Limerick y el Shannon','Limerick se desarrolló en un punto estratégico del río Shannon. Hubo un asentamiento vikingo y después un importante núcleo normando. Controlar el puente y la navegación significaba dominar una de las principales rutas del oeste de Irlanda.'],
  ['La fortaleza normanda','El castillo se levantó a comienzos del siglo XIII durante el reinado de Juan de Inglaterra. Sus torres y murallas responden a una arquitectura militar de gran escala, muy distinta de las casas-torre gaélicas que veremos en Blarney.'],
  ['Los asedios','Limerick desempeñó un papel decisivo en las guerras del siglo XVII. Los asedios de 1690 y 1691 terminaron con el Tratado de Limerick, que marcó el final de la resistencia jacobita organizada en Irlanda y dejó una memoria política muy duradera.'],
  ['Nuestra visita','Nos centraremos en el castillo y en su relación con el río. No intentaremos recorrer la ciudad: Bunratty tiene una hora límite y debe conservarse margen suficiente para llegar antes de las 16:00.']
 ]},
 'bunratty-castle-y-folk-park':{title:'Bunratty Castle & Folk Park',country:'Irlanda',day:6,lead:'Un castillo del siglo XV y un parque de historia social que permiten pasar de las élites medievales a la vida cotidiana irlandesa.',sections:[
  ['Un lugar estratégico','Bunratty se encuentra cerca del estuario del Shannon, en una zona importante para las comunicaciones entre Limerick, Clare y la costa. Hubo fortificaciones anteriores, pero el gran castillo actual fue levantado en el siglo XV y estuvo vinculado a los MacNamara y después a los O’Brien.'],
  ['Castillo y residencia','Sus torres y gran bloque central muestran cómo una residencia aristocrática podía combinar defensa y representación. Los interiores amueblados permiten imaginar el edificio como una casa habitada, no simplemente como una ruina romántica.'],
  ['El Folk Park','El parque reúne y recrea casas rurales, tiendas, escuela, iglesia y otros edificios de los siglos XIX y principios del XX. Después de visitar castillos, es una oportunidad excelente para acercarse a la vida cotidiana de agricultores, artesanos y comerciantes.'],
  ['La hora manda','La última entrada indicada es a las 16:00. Esa referencia debe gobernar toda la jornada. Una vez dentro podremos administrar el tiempo, pero llegar tarde significaría perder una de las nuevas visitas más interesantes del itinerario.']
 ]},
 'galway':{title:'Galway',country:'Irlanda',day:7,lead:'Una ciudad atlántica de raíces medievales que se disfruta tanto por su historia como por la música, las calles y el ambiente.',sections:[
  ['Puerto medieval','Galway creció como ciudad amurallada y puerto comercial. Su posición en la desembocadura del Corrib facilitó relaciones con Gran Bretaña, Francia y la península ibérica. El centro actual conserva la escala compacta de aquella ciudad mercantil.'],
  ['Las Tribes of Galway','Durante siglos un grupo de familias mercantiles dominó la política urbana. Más tarde serían conocidas como las Fourteen Tribes of Galway. El término nació como una burla, pero terminó adoptándose con orgullo. Lynch’s Castle recuerda todavía la riqueza y poder de esas familias.'],
  ['España y el Spanish Arch','El comercio con la península ibérica fue importante. El Spanish Arch no fue construido por españoles: formaba parte de las defensas junto a los muelles. Su nombre posterior refleja la memoria de esos vínculos marítimos.'],
  ['Claddagh','Al otro lado del Corrib estaba Claddagh, una comunidad pesquera con fuerte identidad propia. Su nombre está asociado al famoso anillo de dos manos que sostienen un corazón coronado, símbolo de amistad, amor y lealtad.'],
  ['Música y cultura','Galway es una puerta natural hacia Connemara y hacia regiones donde el irlandés conserva presencia. Universidad, festivales, teatro y música tradicional dan a la ciudad una vida cultural muy intensa. La música callejera de Shop Street y Quay Street es parte de esa identidad.'],
  ['Qué ver sin convertirlo en una carrera','Eyre Square, Shop Street, Lynch’s Castle, St Nicholas, Quay Street y Spanish Arch forman un recorrido compacto. La catedral y la ribera del Corrib pueden añadirse con facilidad. Pero Galway se disfruta mejor dejando huecos: una tienda, un músico o un pub pueden ser tan memorables como un monumento.'],
  ['La ventaja del nuevo itinerario','Disponer de la tarde completa después de Moher es una gran mejora. Podremos comer, dividirnos por familias y volver a reunirnos más tarde. La ciudad necesita precisamente ese tipo de visita flexible.']
 ]},
 'el-burren':{title:'El Burren',country:'Irlanda',day:7,lead:'Un paisaje calizo aparentemente desnudo que esconde una extraordinaria diversidad natural y una larga presencia humana.',sections:[
  ['Un paisaje kárstico','La superficie está formada por grandes losas de caliza separadas por grietas. El agua se infiltra con rapidez y circula bajo tierra, creando cavidades, cuevas y conductos. Esa falta de agua superficial contribuye a la apariencia austera del territorio.'],
  ['Una flora inesperada','En las grietas protegidas crecen especies que normalmente asociaríamos a regiones muy diferentes. Plantas atlánticas, alpinas y mediterráneas pueden encontrarse muy próximas entre sí gracias a la combinación de microclimas, roca caliza y prácticas ganaderas tradicionales.'],
  ['Paisaje cultural','Muros de piedra seca, restos arqueológicos y pequeñas explotaciones recuerdan que el Burren no es un espacio vacío. Las comunidades humanas se han adaptado durante milenios a un suelo que a primera vista parece poco favorable.']
 ]},
 'acantilados-de-moher':{title:'Acantilados de Moher',country:'Irlanda',day:7,lead:'Una pared de roca frente al Atlántico donde la geología, el viento y las aves forman una sola experiencia.',sections:[
  ['Cómo se formaron','Los acantilados están compuestos por capas de areniscas, limos y lutitas depositadas hace cientos de millones de años. La erosión marina socava la base y abre fracturas; los desprendimientos resultantes mantienen el frente abrupto.'],
  ['Una colonia de aves marinas','Los cortados ofrecen lugares de nidificación inaccesibles para muchos depredadores. En temporada pueden verse fulmares, araos, alcas y, con algo de suerte, frailecillos. Unos pequeños prismáticos ayudan mucho más que acercarse al borde.'],
  ['La experiencia depende del tiempo','Sol, lluvia, niebla y viento cambian por completo la percepción del lugar. La roca puede pasar del ocre al gris casi negro en minutos. No hace falta un cielo despejado para disfrutar de Moher: el mal tiempo puede intensificar su carácter atlántico.']
 ]},
 'dublin':{title:'Dublín',country:'Irlanda',day:8,lead:'Una capital junto al Liffey donde se superponen herencias vikingas, medievales, británicas, independentistas y literarias.',sections:[
  ['Dos nombres para una ciudad','Dublin procede de Dubh Linn, “laguna negra”. El nombre irlandés, Baile Átha Cliath, recuerda el asentamiento del vado. Ambos nombres reflejan dos núcleos próximos que terminaron formando la ciudad. El Liffey y el acceso al mar fueron determinantes desde el principio.'],
  ['La ciudad vikinga','Los vikingos establecieron un asentamiento permanente en el siglo IX y convirtieron Dublín en un importante centro comercial. Sus conexiones alcanzaban Gran Bretaña, Escandinavia y el Atlántico. El entorno de Christ Church se encuentra en el corazón de aquella ciudad medieval que creció sobre bases vikingas.'],
  ['Dublin Castle','Después de la conquista anglonormanda, Dublín se convirtió en centro del poder inglés en Irlanda. Dublin Castle, iniciado a comienzos del siglo XIII, fue durante siglos sede de administración y gobierno. En 1922 fue entregado al nuevo Estado Libre Irlandés, un gesto cargado de simbolismo.'],
  ['La ciudad georgiana','En el siglo XVIII Dublín experimentó una gran expansión. Plazas, casas de ladrillo, puertas de colores y amplias calles crearon la imagen georgiana visible en Merrion Square o Fitzwilliam Square. En aquella época era una de las grandes ciudades del Imperio británico y sede de un Parlamento irlandés hasta 1801.'],
  ['Trinity College y el Book of Kells','Trinity College fue fundado en 1592. Su biblioteca conserva el Book of Kells, manuscrito iluminado realizado alrededor del año 800 y una de las grandes obras del arte medieval europeo. Nuestro tiempo puede impedir una visita interior, pero el lugar explica parte del prestigio cultural de Dublín.'],
  ['1916 e independencia','La ciudad fue escenario central del Levantamiento de Pascua de 1916 y del proceso que condujo a la independencia. El General Post Office quedó ligado a la rebelión y Dublin Castle simbolizaba la administración británica. Edificios y monumentos de la capital conservan memorias políticas muy diferentes.'],
  ['Una ciudad literaria','Swift, Wilde, Yeats, Joyce y Beckett son algunos de los escritores ligados a Dublín. Joyce convirtió calles, pubs y ciudadanos corrientes en literatura universal. La UNESCO reconoce a Dublín como Ciudad de la Literatura. Su identidad cultural depende tanto de los libros y el teatro como de los monumentos.'],
  ['Temple Bar con perspectiva','Temple Bar es conocido por los pubs, pero también concentra instituciones culturales y una trama de calles que merece recorrerse temprano. En nuestro paseo exprés funciona como enlace natural entre Dublin Castle y el Liffey.'],
  ['Una primera impresión, no una visita completa','El último día es muy corto. No intentaremos “hacer Dublín”. Christ Church, Dublin Castle, Dame Street y el borde de Temple Bar son suficientes para obtener una primera impresión sin comprometer el vuelo. La ciudad merece otra visita en el futuro.']
 ]}
};


const DETAIL_ALIASES={
 'killarney-national-park':'anillo-de-kerry','ladies-view':'anillo-de-kerry','moll-s-gap':'anillo-de-kerry','kenmare':'anillo-de-kerry','sneem':'anillo-de-kerry','cahersiveen':'anillo-de-kerry',
 'king-john-s-castle':'king-john-s-castle','bunratty-castle-y-folk-park':'bunratty-castle-y-folk-park',
 'latin-quarter-y-quay-street':'galway','spanish-arch-y-claddagh':'galway'
};

function slugify(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,'y').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function routeLink(n){const r=ROUTES[n]; if(!r) return null; const p=r.points; const origin=p[0], destination=p[p.length-1], waypoints=p.slice(1,-1).join('|'); return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}${waypoints?`&waypoints=${encodeURIComponent(waypoints)}`:''}&travelmode=${r.mode}`;}
function detailSlug(name){const slug=slugify(name);return PLACE_DETAILS[slug]?slug:(DETAIL_ALIASES[slug]||null);}
function detailFor(name){const slug=detailSlug(name);return slug?PLACE_DETAILS[slug]:null;}

function mapsLink(q){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function todayNumber(){const now=new Date(); if(now.getFullYear()!==2026||now.getMonth()!==7) return null; const d=now.getDate(); return d>=13&&d<=20?d-12:null;}
function dayCard(d){const today=todayNumber()===d.n?' today':'';return `<a class="card day-card${today}" href="#dia-${d.n}"><div class="day-number">Día ${d.n} · ${d.date}</div><h3>${d.title}</h3><p>${d.subtitle}</p><div class="badges">${d.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div></a>`}
function renderHome(){const t=todayNumber(),hero=PHOTOS[1];return `<section class="hero hero-photo" id="inicio" style="--hero-image:url('${hero.url}')"><div class="hero-inner"><div class="eyebrow">13–20 agosto 2026 · 23 viajeros</div><h1>Escocia e Irlanda en familia</h1><p>Guía digital ampliada con itinerario, rutas, historia, lugares, hoteles y datos prácticos para leer y consultar antes y durante el viaje.</p><div class="hero-actions"><a class="btn" href="#dias">Ver los 8 días</a><a class="btn secondary" href="#historia">Historia y contexto</a></div><div class="stats"><div class="stat"><strong>8</strong><span>días</span></div><div class="stat"><strong>2</strong><span>países</span></div><div class="stat"><strong>23</strong><span>viajeros</span></div><div class="stat"><strong>5</strong><span>coches en Irlanda</span></div></div><div class="photo-credit"><a href="${hero.source}" target="_blank">Foto: ${hero.credit}</a></div></div></section>${t?`<section class="container"><div class="today-panel"><div class="card today-main"><div class="eyebrow">Hoy toca</div><h2>Día ${t} · ${DAYS[t-1].title}</h2><p>${DAYS[t-1].summary}</p><a class="btn secondary" href="#dia-${t}">Abrir jornada</a></div><div class="card today-side"><div><div class="day-number">Dormimos en</div><div class="big">${DAYS[t-1].sleep}</div></div><div class="muted">${DAYS[t-1].date}</div></div></div></section>`:''}<section class="container"><div class="section-title"><div><div class="eyebrow" style="color:var(--accent-2)">Mapa general</div><h2>La ruta completa</h2></div><p>Mapa interactivo orientativo de Escocia e Irlanda.</p></div><div class="map-card"><div id="tripMap" class="map"></div></div></section><section class="container" id="dias"><div class="section-title"><div><div class="eyebrow" style="color:var(--accent-2)">Itinerario</div><h2>El viaje de un vistazo</h2></div><p>Toca cualquier jornada para abrir horarios, lugares, contexto y recomendaciones.</p></div><div class="grid">${DAYS.map(dayCard).join('')}</div></section><section class="container home-links"><div class="grid"><a class="card feature-link" href="#historia"><div class="day-number">Antes de viajar</div><h3>Historia de Escocia e Irlanda</h3><p>Dos introducciones pensadas para entender mejor lo que iremos viendo.</p></a><a class="card feature-link" href="#lugares"><div class="day-number">Lectura</div><h3>Lugares del viaje</h3><p>Fichas ampliadas para leer antes de cada parada.</p></a><a class="card feature-link" href="#hoteles"><div class="day-number">Alojamiento</div><h3>Hoteles y datos de contacto</h3><p>Direcciones, teléfonos, noches y acceso rápido a Google Maps.</p></a></div></section>`}
function renderDay(n){
 const d=DAYS.find(x=>x.n===n)||DAYS[0],ph=PHOTOS[d.n],route=routeLink(d.n);
 return `<section class="day-hero day-photo" style="--day-image:url('${ph.url}')"><div class="container"><a class="back" href="#dias">← Todos los días</a><div class="eyebrow">Día ${d.n} · ${d.date} · Noche: ${d.sleep}</div><h1>${d.title}</h1><p>${d.subtitle}</p><div class="day-progress"><span style="width:${d.n/8*100}%"></span></div><div class="photo-credit"><a href="${ph.source}" target="_blank">Foto: ${ph.credit}</a></div></div></section><section class="container"><div class="card"><h2>Resumen del día</h2><p>${d.summary}</p></div><div class="section-title"><div><div class="eyebrow" style="color:var(--accent-2)">Ruta</div><h2>Mapa de la jornada</h2></div><p>Marcadores orientativos de las principales paradas.</p></div><div class="map-card"><div id="dayMap" class="map day-map"></div></div>${route?`<div class="actions route-actions"><a class="btn" target="_blank" rel="noopener" href="${route}">🧭 Abrir ruta del día en Google Maps</a></div>`:`<div class="callout compact"><strong>Ruta del día</strong>Este día combina desplazamientos urbanos, traslado al aeropuerto y vuelo; no se representa como una única ruta de carretera.</div>`}<div class="section-title"><h2>Horario</h2></div><div class="card schedule">${d.schedule.map(r=>`<div class="schedule-row"><div class="time">${r[0]}</div><div>${r[1]}</div></div>`).join('')}</div><div class="section-title"><div><h2>Lugares</h2></div><p>Resumen para la jornada. Las fichas ampliadas permiten leer con más calma antes de llegar.</p></div>${d.places.map(p=>{const det=detailFor(p[0]);return `<article class="card place"><h3>${p[0]}</h3><p>${p[1]}</p><div class="actions">${det?`<a class="btn" href="#lugar-${detailSlug(p[0])}">Leer más →</a>`:''}<a class="btn secondary" target="_blank" rel="noopener" href="${mapsLink(p[0])}">📍 Abrir en Maps</a></div></article>`}).join('')}<div class="callout"><strong>Cinco minutos antes de llegar</strong>${d.before}</div><div class="callout"><strong>Si solo pudiera recomendar una cosa de hoy…</strong>${d.recommend}</div><div class="actions"><a class="btn secondary" href="#dia-${Math.max(1,n-1)}">← Día anterior</a><a class="btn" href="#dia-${Math.min(8,n+1)}">Día siguiente →</a></div></section>`
}
function renderPlaces(){const entries=Object.entries(PLACE_DETAILS);return `<section class="page-head"><div class="container"><div class="eyebrow">Para leer antes de llegar</div><h1>Lugares del viaje</h1><p>Fichas más amplias para quienes quieran conocer la historia, el paisaje y el contexto de cada parada.</p></div></section><section class="container"><div class="places-index">${entries.map(([slug,p])=>`<a class="card place-index-card" href="#lugar-${slug}"><div class="day-number">${p.country} · Día ${p.day}</div><h3>${p.title}</h3><p>${p.lead}</p><span class="text-link">Leer ficha →</span></a>`).join('')}</div></section>`}
function renderPlace(slug){const p=PLACE_DETAILS[slug]; if(!p)return renderPlaces(); return `<section class="page-head place-head"><div class="container"><a class="back" href="#dia-${p.day}">← Volver al Día ${p.day}</a><div class="eyebrow">${p.country} · Día ${p.day}</div><h1>${p.title}</h1><p>${p.lead}</p><div class="actions"><a class="btn" target="_blank" rel="noopener" href="${mapsLink(p.title)}">📍 Abrir en Maps</a></div></div></section><section class="container reading">${p.sections.map(s=>`<article class="card reading-section"><h2>${s[0]}</h2><p>${s[1]}</p></article>`).join('')}<div class="actions"><a class="btn secondary" href="#dia-${p.day}">← Volver a la jornada</a><a class="btn" href="#lugares">Todas las fichas</a></div></section>`}
function historyBlock(key){const h=HISTORY[key];return `<article class="history-block"><div class="day-number">${key==='scotland'?'Escocia':'Irlanda'}</div><h2>${h.title}</h2><p class="history-intro">${h.intro}</p>${h.sections.map(s=>`<section class="card history-section"><h3>${s[0]}</h3><p>${s[1]}</p></section>`).join('')}</article>`}
function renderHistory(){return `<section class="page-head"><div class="container"><div class="eyebrow">Contexto</div><h1>Historia para entender el viaje</h1><p>No es un manual de historia: son las claves necesarias para que castillos, ciudades y paisajes tengan más sentido cuando estemos allí.</p></div></section><section class="container history-wrap">${historyBlock('scotland')}${historyBlock('ireland')}</section>`}
function renderHotels(){return `<section class="page-head"><div class="container"><div class="eyebrow">Alojamiento</div><h1>Hoteles</h1><p>Información de consulta rápida durante el viaje.</p></div></section><section class="container" id="hoteles"><div class="grid">${HOTELS.map(h=>`<article class="card hotel-card"><div class="day-number">${h.city}</div><h3>${h.name}</h3><div class="hotel-meta"><div>${h.address}</div><div><strong>Noches:</strong> ${h.nights}</div>${h.phone?`<div><strong>Tel.</strong> ${h.phone}</div>`:''}${h.email?`<div><strong>Email.</strong> ${h.email}</div>`:''}<div class="hotel-note">${h.note}</div></div><div class="actions"><a class="btn" target="_blank" rel="noopener" href="${mapsLink(h.name+' '+h.address)}">📍 Maps</a>${h.phone?`<a class="btn secondary" href="tel:${h.phone.replace(/\s/g,'')}">☎ Llamar</a>`:''}</div></article>`).join('')}</div></section>`}
function renderPractical(){return `<section class="page-head"><div class="container"><div class="eyebrow">Consulta rápida</div><h1>Información práctica</h1><p>Lo esencial para tener a mano sin abrir el documento Word.</p></div></section><section class="container" id="practico"><div class="quick-list">${practical.map(p=>`<div class="quick-item"><strong>${p[0]}</strong><div class="muted">${p[1]}</div></div>`).join('')}</div></section>`}
function baseMap(id){if(typeof L==='undefined')return null;return L.map(id,{scrollWheelZoom:false})}
function addTiles(m){L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(m)}
function initTripMap(){const el=document.getElementById('tripMap');if(!el||el._leaflet_id)return;const m=baseMap('tripMap');if(!m)return;addTiles(m);const pts=[[55.9533,-3.1883],[56.6826,-5.1023],[57.4778,-4.2247],[56.945,-2.197],[56.3398,-2.7967],[51.8985,-8.4756],[51.9668,-9.5931],[51.8507,-8.294],[53.2707,-9.0568],[52.9715,-9.4309],[53.3498,-6.2603]];L.polyline(pts,{color:'#b88b4a',weight:3,opacity:.8,dashArray:'8 8'}).addTo(m);[['Edimburgo',55.9533,-3.1883],['Cork',51.8985,-8.4756],['Galway',53.2707,-9.0568],['Dublín',53.3498,-6.2603]].forEach(p=>L.marker([p[1],p[2]]).addTo(m).bindPopup(`<strong>${p[0]}</strong>`));m.fitBounds(pts,{padding:[25,25]})}
function initDayMap(n){const el=document.getElementById('dayMap');if(!el||el._leaflet_id)return;const data=DAY_POINTS[n]||[],m=baseMap('dayMap');if(!m)return;addTiles(m);const pts=data.map(p=>[p[1],p[2]]);L.polyline(pts,{color:'#b88b4a',weight:4,opacity:.9}).addTo(m);data.forEach((p,i)=>L.marker([p[1],p[2]]).addTo(m).bindPopup(`<strong>${i+1}. ${p[0]}</strong>`));m.fitBounds(pts,{padding:[25,25]})}
function renderCredits(){const uniq=Object.values(PHOTOS).filter((x,i,a)=>a.findIndex(y=>y.source===x.source)===i);return `<section class="page-head"><div class="container"><div class="eyebrow">Imágenes y cartografía</div><h1>Créditos</h1><p>Fotografías de Wikimedia Commons y mapas de OpenStreetMap.</p></div></section><section class="container"><div class="grid">${uniq.map(p=>`<article class="card credit-card"><img src="${p.url}" alt="${p.caption}" loading="lazy"><h3>${p.caption}</h3><p class="muted">${p.credit}</p><a class="btn secondary" target="_blank" href="${p.source}">Ver ficha y licencia</a></article>`).join('')}</div><div class="callout"><strong>Cartografía</strong>Leaflet + OpenStreetMap. Las líneas de ruta son orientativas; para navegación real, usar Google Maps.</div></section>`}
function router(){let h=location.hash||'#inicio';document.getElementById('mainNav').classList.remove('open');if(h.startsWith('#dia-')){const n=Number(h.split('-')[1]);document.getElementById('app').innerHTML=renderDay(n);setTimeout(()=>initDayMap(n),50);}else if(h==='#dias'){document.getElementById('app').innerHTML=renderHome();setTimeout(()=>{initTripMap();document.getElementById('dias')?.scrollIntoView();},50);}else if(h.startsWith('#lugar-')){document.getElementById('app').innerHTML=renderPlace(h.slice(7));}else if(h==='#lugares'){document.getElementById('app').innerHTML=renderPlaces();}else if(h==='#historia'){document.getElementById('app').innerHTML=renderHistory();}else if(h==='#hoteles'){document.getElementById('app').innerHTML=renderHotels();}else if(h==='#practico'){document.getElementById('app').innerHTML=renderPractical();}else if(h==='#creditos'){document.getElementById('app').innerHTML=renderCredits();}else{document.getElementById('app').innerHTML=renderHome();setTimeout(initTripMap,50);}window.scrollTo(0,0)}
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));
window.addEventListener('hashchange',router);router();